#include<iostream>
#include<vector>
using namespace std;
struct place {
    string province;
    string district;
    string type;
    string name;
    int price;
};
vector<place>allplace = {
   // --- Chiang Mai ---
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Phra That Doi Suthep", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Tha Phae Gate", 0},
{"Chiang Mai", "Chom Thong", "Adventure", "Doi Inthanon National Park", 100},
{"Chiang Mai", "Chom Thong", "Natural", "Khun Thongdee Hydrangea Garden, Inthanon", 50},
{"Chiang Mai", "Mae Rim", "Natural", "Jinjoo Orange Garden, Mon Jam", 80},
{"Chiang Mai", "Hang Dong", "Adventure", "Grand Canyon Hang Dong", 50},
{"Chiang Mai", "Mae Rim", "Natural", "Queen Sirikit Botanic Garden", 40},
{"Chiang Mai", "Mueang Chiang Mai", "Cafe", "Baan Kang Wat", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Umong", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Natural", "Chiang Mai Zoo", 130},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Phra Singh Woramahawihan", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Suan Dok", 0},
{"Chiang Mai", "Chiang Dao", "Adventure", "Doi Luang Chiang Dao", 700},
{"Chiang Mai", "Mae Rim", "Natural", "Maesa Elephant Camp", 100},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Chedi Luang Worawihan", 0},
{"Chiang Mai", "Mae Taeng", "Adventure", "Doi Mon Ngo", 800},
{"Chiang Mai", "Mueang Chiang Mai", "Photo", "Khlong Mae Kha", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Photo", "One Nimman", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Phan Tao", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Culture", "Wat Chet Yot", 0},
{"Chiang Mai", "Chom Thong", "Natural", "Ang Ka", 0},
{"Chiang Mai", "Mueang Chiang Mai", "Natural", "Khun Chang Khian", 150},

// --- Chiang Rai ---
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Wat Rong Khun", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Wat Rong Suea Ten", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Wat Huay Pla Kang", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Wat Phra Kaew", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Wat Phra That Doi Chom Thong", 0},
{"Chiang Rai", "Mae Suai", "Culture", "Wat Saeng Kaeo Phothiyan", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Baan Dam Museum", 80},
{"Chiang Rai", "Mae Sai", "Culture", "Doi Tung Royal Villa", 90},
{"Chiang Rai", "Thoeng", "Adventure", "Phu Chi Fa", 1600},
{"Chiang Rai", "Wiang Kaen", "Adventure", "Doi Pha Tang", 1700},
{"Chiang Rai", "Wiang Kaen", "Adventure", "Phu Chi Dao", 1500},
{"Chiang Rai", "Wiang Kaen", "Adventure", "Phu Chi Long", 1200},
{"Chiang Rai", "Mae Suai", "Adventure", "Doi Chang", 1600},
{"Chiang Rai", "Mae Fa Luang", "Adventure", "Doi Mae Salong", 1200},
{"Chiang Rai", "Mae Sai", "Adventure", "Tham Luang-Khun Nam Nang Non National Park", 950},
{"Chiang Rai", "Chiang Saen", "Natural", "Golden Triangle", 300},
{"Chiang Rai", "Mueang Chiang Rai", "Natural", "Singha Park (Boon Rawd Farm)", 300},
{"Chiang Rai", "Mae Chan", "Photo", "Choui Fong Tea Plantation", 0},
{"Chiang Rai", "Mae Sai", "Natural", "Mae Fah Luang Garden (Doi Tung)", 90},
{"Chiang Rai", "Mueang Chiang Rai", "Culture", "Rai Cherntawan", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Photo", "Chiang Rai Clock Tower", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Photo", "Chiang Rai Night Bazaar", 0},
{"Chiang Rai", "Mueang Chiang Rai", "Photo", "Chiang Rai Walking Street", 0},
{"Chiang Rai", "Mae Suai", "Photo", "Skywalk Wat Saeng Kaeo Phothiyan", 40},

// --- Mae Hong Son ---
{"Mae Hong Son", "Khun Yuam", "Natural", "Bua Tong Fields, Doi Mae U Kho", 0},
{"Mae Hong Son", "Mueang Mae Hong Son", "Natural", "Pang Oung", 200},
{"Mae Hong Son", "Mueang Mae Hong Son", "Culture", "Ban Rak Thai", 370},
{"Mae Hong Son", "Pang Mapha", "Photo", "Doi Kiew Lom Viewpoint", 100},
{"Mae Hong Son", "Pang Mapha", "Adventure", "Tham Nam Lot National Park", 160},
{"Mae Hong Son", "Mueang Mae Hong Son", "Natural", "Tham Pla", 20},
{"Mae Hong Son", "Mueang Mae Hong Son", "Natural", "Pha Suea Waterfall", 20},
{"Mae Hong Son", "Khun Yuam", "Natural", "Mae Surin Waterfall", 40},
{"Mae Hong Son", "Pai", "Adventure", "Kong Lan (Pai Canyon)", 0},
{"Mae Hong Son", "Mueang Mae Hong Son", "Culture", "Wat Phra That Doi Kong Mu", 0},
{"Mae Hong Son", "Mueang Mae Hong Son", "Culture", "Wat Chong Kham, Wat Chong Klang", 0},
{"Mae Hong Son", "Pai", "Culture", "Wat Phra That Mae Yen", 0},
{"Mae Hong Son", "Pai", "Culture", "Wat Nam Hu", 0},
{"Mae Hong Son", "Pai", "Photo", "Pai Memorial Bridge", 0},
{"Mae Hong Son", "Mueang Mae Hong Son", "Culture", "Su Tong Pae Bridge", 20},
{"Mae Hong Son", "Pai", "Photo", "Pai Walking Street", 0},
{"Mae Hong Son", "Pai", "Photo", "Santichon Village", 0},
{"Mae Hong Son", "Pai", "Photo", "Kho Ku So Bridge", 20},
{"Mae Hong Son", "Mueang Mae Hong Son", "Culture", "Long Neck Karen Village, Huay Suea Thao", 300},
{"Mae Hong Son", "Mueang Mae Hong Son", "Natural", "Phu Klon Country Club", 80},
{"Mae Hong Son", "Mueang Mae Hong Son", "Photo", "Lee Wine Rak Thai", 40},

// --- Lamphun ---
{"Lamphun", "Li", "Natural", "Kaeng Ko (Mae Ping National Park)", 220},
{"Lamphun", "Li", "Natural", "Thung Kik", 50},
{"Lamphun", "Li", "Adventure", "Pha Daeng Luang Viewpoint", 1280},
{"Lamphun", "Li", "Natural", "Ko Luang Waterfall", 50},
{"Lamphun", "Mueang Lamphun", "Adventure", "Doi Ngum", 50},
{"Lamphun", "Thung Hua Chang", "Natural", "Mae Mang Reservoir", 50},
{"Lamphun", "Mae Tha", "Natural", "Tham Erawan Waterfall", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Wat Phra That Hariphunchai Woramahawihan", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Wat Jamadevi", 0},
{"Lamphun", "Pa Sang", "Culture", "Wat Phra Phutthabat Tak Pha", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Wat San Pa Yang Luang", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Wat Mahawan", 0},
{"Lamphun", "Li", "Culture", "Wat Phra Phutthabat Huai Tom", 0},
{"Lamphun", "Li", "Culture", "Phra Mahathat Chedi Si Wiang Chai", 0},
{"Lamphun", "Li", "Culture", "Wat Phra That Inthakhwaen", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Queen Jamadevi Monument", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Ku Chang Ku Ma", 0},
{"Lamphun", "Mae Tha", "Photo", "Tha Chomphu Bridge", 0},
{"Lamphun", "Mae Tha", "Adventure", "Doi Khun Tan National Park", 20},
{"Lamphun", "Li", "Culture", "Ban Phra Bat Huai Tom Community", 0},
{"Lamphun", "Mueang Lamphun", "Culture", "Hariphunchai Hand-Woven Fabric Institute", 0},
{"Lamphun", "Pa Sang", "Culture", "Ban Don Luang (Hand-Woven Cotton)", 0},

// --- Lampang ---
{"Lampang", "Ko Kha", "Culture", "Wat Phra That Lampang Luang", 0},
{"Lampang", "Mueang Lampang", "Culture", "Wat Si Rong Mueang", 0},
{"Lampang", "Mae Tha", "Culture", "Wat Phra That Doi Phra Chan", 0},
{"Lampang", "Mueang Lampang", "Culture", "Wat Pong Sanuk Nuea", 0},
{"Lampang", "Chae Hom", "Culture", "Wat Chaloem Phra Kiat Phrachomklao Rachanusorn", 0},
{"Lampang", "Mueang Lampang", "Culture", "Wat Phra Chedi Sao Lang", 0},
{"Lampang", "Chae Hom", "Culture", "Wat Akho Chai Khiri", 0},
{"Lampang", "Mueang Pan", "Natural", "Chae Son National Park", 120},
{"Lampang", "Ngao", "Natural", "Lom Phu Khiao", 0},
{"Lampang", "Mae Mo", "Natural", "Mae Mo Sunflower Field", 0},
{"Lampang", "Mae Mo", "Natural", "Mae Mo Botanic Garden", 20},
{"Lampang", "Mueang Lampang", "Natural", "Kio Lom Reservoir", 0},
{"Lampang", "Mueang Lampang", "Photo", "Kad Kong Ta", 0},
{"Lampang", "Mueang Lampang", "Culture", "Baan Sao Nak", 50},
{"Lampang", "Mueang Lampang", "Photo", "Ratsadaphisek Bridge", 0},
{"Lampang", "Hang Chat", "Natural", "Thai Elephant Conservation Center", 100},
{"Lampang", "Mueang Lampang", "Culture", "Thanabodi Ceramic Museum", 100},
{"Lampang", "Mueang Lampang", "Photo", "Lampang Art Gallery", 0},
{"Lampang", "Mueang Lampang", "Photo", "Lampang Railway Station", 0},
{"Lampang", "Mae Mo", "Photo", "Mae Mo Mine", 30},
{"Lampang", "Mueang Lampang", "Photo", "Lampang Clock Tower Roundabout", 0},

// --- Phayao ---
{"Phayao", "Mueang Phayao", "Natural", "Phayao Lake (Kwan Phayao)", 30},
{"Phayao", "Mueang Phayao", "Culture", "Pho Khun Ngam Mueang Monument", 0},
{"Phayao", "Mueang Phayao", "Culture", "Wat Phra That Chom Thong", 0},
{"Phayao", "Mueang Phayao", "Culture", "Wat Si Khom Kham", 0},
{"Phayao", "Mueang Phayao", "Culture", "Wat Tilok Aram", 30},
{"Phayao", "Chiang Kham", "Culture", "Wat Nantaram", 0},
{"Phayao", "Chiang Kham", "Culture", "Wat Phra Nang Din", 0},
{"Phayao", "Mueang Phayao", "Adventure", "Phra That Doi Nok Chedi", 1100},
{"Phayao", "Mueang Phayao", "Culture", "Phayao City Pillar Shrine", 0},
{"Phayao", "Pong", "Adventure", "Phu Langka National Park", 50},
{"Phayao", "Phu Sang", "Adventure", "Phu Sang National Park", 50},
{"Phayao", "Chiang Muan", "Adventure", "Doi Phu Nang National Park", 50},
{"Phayao", "Mae Chai", "Adventure", "Mae Puem National Park", 50},
{"Phayao", "Mueang Phayao", "Adventure", "Doi Luang, Doi Nok", 50},
{"Phayao", "Mueang Phayao", "Adventure", "Pha Hua Ruea", 50},
{"Phayao", "Phu Sang", "Natural", "Phu Sang Waterfall", 50},
{"Phayao", "Mueang Phayao", "Natural", "Mae Tam Reservoir", 0},
{"Phayao", "Chiang Muan", "Natural", "Than Sawan Waterfall", 50},
{"Phayao", "Chiang Muan", "Natural", "Huai Ton Phueng Waterfall", 50},
{"Phayao", "Mueang Phayao", "Natural", "Champa Thong Waterfall", 50},
{"Phayao", "Mae Chai", "Natural", "Mae Puem Reservoir", 50},
{"Phayao", "Mueang Phayao", "Photo", "Rai Phu Klong Hill", 120},
{"Phayao", "Chiang Kham", "Culture", "Tai Lue Mae Saeng Da House", 0},

// --- Phrae ---
{"Phrae", "Mueang Phrae", "Culture", "Wat Phra That Cho Hae", 0},
{"Phrae", "Mueang Phrae", "Culture", "Wat Phra That Chom Chaeng", 0},
{"Phrae", "Mueang Phrae", "Culture", "Phrae City Pillar Shrine", 0},
{"Phrae", "Mueang Phrae", "Culture", "Wat Phong Sunan", 0},
{"Phrae", "Mueang Phrae", "Culture", "Wat Chom Sawan", 0},
{"Phrae", "Mueang Phrae", "Culture", "Replica Phra That Inthakhwaen", 0},
{"Phrae", "Mueang Phrae", "Culture", "Phra That Doi Leng", 0},
{"Phrae", "Den Chai", "Culture", "Wat Phra That Suthon", 0},
{"Phrae", "Rong Kwang", "Culture", "Wat Phra That Pu Chae", 0},
{"Phrae", "Mueang Phrae", "Culture", "Wat Na Khuha (Phra Chao Ton Luang)", 0},
{"Phrae", "Mueang Phrae", "Culture", "Wongburi House (Pink House)", 50},
{"Phrae", "Mueang Phrae", "Culture", "Khum Chao Luang", 0},
{"Phrae", "Mueang Phrae", "Culture", "Khum Wichairacha", 0},
{"Phrae", "Long", "Photo", "Ban Pin Railway Station", 0},
{"Phrae", "Long", "Culture", "Komon Antique Textile Museum", 0},
{"Phrae", "Mueang Phrae", "Natural", "Phae Mueang Phi Forest Park", 50},
{"Phrae", "Long", "Adventure", "Doi Pha Klong National Park (Suan Hin Maharaj)", 50},
{"Phrae", "Wang Chin", "Adventure", "Wiang Kosai National Park", 40},
{"Phrae", "Song", "Adventure", "Mae Yom National Park (Kaeng Suea Ten)", 50},
{"Phrae", "Rong Kwang", "Adventure", "Pha Nang Khoi Cave", 0},
{"Phrae", "Rong Kwang", "Natural", "Mae Thang Reservoir", 100},
{"Phrae", "Rong Kwang", "Natural", "Huai Rong Waterfall", 0},
{"Phrae", "Mueang Phrae", "Culture", "Ban Na Khuha", 0},

// --- Nan ---
{"Nan", "Phu Phiang", "Culture", "Wat Phra That Chae Haeng", 0},
{"Nan", "Mueang Nan", "Culture", "Wat Phumin", 0},
{"Nan", "Mueang Nan", "Culture", "Wat Ming Mueang", 0},
{"Nan", "Mueang Nan", "Culture", "Wat Phra That Khao Noi", 0},
{"Nan", "Mueang Nan", "Culture", "Wat Si Phan Ton", 0},
{"Nan", "Mueang Nan", "Culture", "Wat Phra That Chang Kham", 0},
{"Nan", "Pua", "Culture", "Wat Ton Laeng", 0},
{"Nan", "Tha Wang Pha", "Culture", "Wat Nong Bua", 0},
{"Nan", "Mueang Nan", "Culture", "Hong Chao Fong Kham", 0},
{"Nan", "Mueang Nan", "Culture", "Nan Riverside Art Gallery", 20},
{"Nan", "Mueang Nan", "Culture", "Nan National Museum", 20},
{"Nan", "Chiang Klang", "Photo", "Sab Kon Tobacco Curing Station", 0},
{"Nan", "Na Noi", "Adventure", "Doi Samoe Dao", 50},
{"Nan", "Tha Wang Pha", "Adventure", "Suan Ya Luang", 130},
{"Nan", "Pua", "Photo", "1715 Viewpoint (Doi Phu Kha)", 0},
{"Nan", "Mueang Nan", "Photo", "Doi Ti Du", 0},
{"Nan", "Na Noi", "Natural", "Sao Din Na Noi and Khok Suea", 50},
{"Nan", "Bo Kluea", "Culture", "Ancient Salt Wells", 0},
{"Nan", "Bo Kluea", "Natural", "Sapan Village", 0},
{"Nan", "Pua", "Photo", "Curve Number 3 Road", 0},
{"Nan", "Pua", "Adventure", "Wang Sila Laeng", 0},
{"Nan", "Pua", "Natural", "Wang Nam Pua", 0},
{"Nan", "Mueang Nan", "Photo", "Nan Walking Street (Kad Khuang Mueang)", 0},
{"Nan", "Pua", "Natural", "Tat Luang Waterfall", 0},

// --- Uttaradit ---
{"Uttaradit", "Nam Pat", "Adventure", "Phu Soi Dao National Park", 300},
{"Uttaradit", "Nam Pat", "Natural", "Sai Thip Waterfall", 0},
{"Uttaradit", "Laplae", "Natural", "Mae Phun Waterfall", 0},
{"Uttaradit", "Nam Pat", "Natural", "Ton Sak Yai National Park", 20},
{"Uttaradit", "Tha Pla", "Adventure", "Lam Nam Nan National Park", 50},
{"Uttaradit", "Tha Pla", "Natural", "Nan Riverside Beach, Ban Pha Tao", 50},
{"Uttaradit", "Laplae", "Culture", "Wat Phra Borommathat Thung Yang", 0},
{"Uttaradit", "Laplae", "Culture", "Wat Phra Thaen Sila At", 0},
{"Uttaradit", "Laplae", "Culture", "Wat Don Sak", 0},
{"Uttaradit", "Mueang Uttaradit", "Culture", "Wat Phra Fang Sawangkaburi Muninat", 0},
{"Uttaradit", "Mueang Uttaradit", "Culture", "Wat Tha Thanon", 0},
{"Uttaradit", "Laplae", "Culture", "Wat Thong Laplae", 0},
{"Uttaradit", "Laplae", "Culture", "Wat Dong Sa Kaeo", 0},
{"Uttaradit", "Tha Pla", "Natural", "Sirikit Dam", 50},
{"Uttaradit", "Tha Pla", "Natural", "Huai Nam Ri Reservoir", 0},
{"Uttaradit", "Tha Pla", "Natural", "Chong Khao Khat Earth Dam", 0},
{"Uttaradit", "Laplae", "Culture", "Laplae City", 0},
{"Uttaradit", "Mueang Uttaradit", "Culture", "Phraya Phichai Dap Hak Monument", 0},
{"Uttaradit", "Phichai", "Photo", "Paramin Bridge", 0},

// --- Tak ---
{"Tak", "Umphang", "Adventure", "Pi Tu Kro Waterfall", 1800},
{"Tak", "Umphang", "Adventure", "Thi Lo Su Waterfall", 300},
{"Tak", "Umphang", "Adventure", "Thi Lo Cho Waterfall", 450},
{"Tak", "Umphang", "Adventure", "Thi Lo Le Waterfall", 1300},
{"Tak", "Umphang", "Adventure", "Doi Mamuang Sam Muen", 1200},
{"Tak", "Tha Song Yang", "Adventure", "Le Kwa Do", 1700},
{"Tak", "Tha Song Yang", "Adventure", "Doi Bae Ba Tu", 1200},
{"Tak", "Phop Phra", "Adventure", "Mon Mok Tawan", 500},
{"Tak", "Mae Ramat", "Adventure", "Doi Soi Malai", 500},
{"Tak", "Tha Song Yang", "Adventure", "Doi Mon Klui", 1500},
{"Tak", "Tha Song Yang", "Culture", "Wat Phra That Chulamani Si Siam", 0},
{"Tak", "Mae Sot", "Culture", "Wat Thai Watthanaram", 0},
{"Tak", "Mae Sot", "Culture", "Wat Mani Phraison", 0},
{"Tak", "Ban Tak", "Culture", "Wat Phra Borommathat Ban Tak", 0},
{"Tak", "Mae Sot", "Culture", "Wat Mae Ka Sa", 0},
{"Tak", "Tha Song Yang", "Adventure", "Tham Mae Usu", 50},
{"Tak", "Mae Sot", "Natural", "Blue Cave (Tham Si Fa)", 0},
{"Tak", "Mae Sot", "Natural", "Onsen Pong Kham Ram", 100},
{"Tak", "Mae Sot", "Natural", "Mae Ka Sa Hot Spring", 50},
{"Tak", "Mae Sot", "Natural", "Mae Ka Sa Waterfall", 0},
{"Tak", "Phop Phra", "Natural", "Pha Charoen Waterfall", 70},
{"Tak", "Phop Phra", "Natural", "Pa Wai Waterfall", 70},
{"Tak", "Mae Sot", "Natural", "Thararak Waterfall", 0},
{"Tak", "Tha Song Yang", "Natural", "Chao Doi Waterfall", 70},
{"Tak", "Umphang", "Natural", "Pa La Tha Waterfall", 50},
{"Tak", "Mueang Tak", "Adventure", "Taksin Maharat National Park", 70},
{"Tak", "Mueang Tak", "Adventure", "Lan Sang National Park", 70},
{"Tak", "Tha Song Yang", "Adventure", "Mae Moei National Park", 70},
{"Tak", "Mae Ramat", "Adventure", "Khun Pha Wo National Park", 50},
{"Tak", "Tha Song Yang", "Photo", "Mon Khruba Sai", 70},
{"Tak", "Mueang Tak", "Photo", "200th Anniversary Rattanakosin Somphot Bridge", 0},
{"Tak", "Mueang Tak", "Culture", "Ban Chin Alley", 0},
{"Tak", "Mae Sot", "Photo", "Bamboo Tunnel, Thio Phai Ngam", 0},
{"Tak", "Sam Ngao", "Natural", "Bhumibol Dam", 0},
{"Tak", "Mueang Tak", "Natural", "Huai Mae Tho Reservoir", 0},

// --- Sukhothai ---
{"Sukhothai", "Mueang Sukhothai", "Culture", "Sukhothai Historical Park", 70},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Mahathat", 50},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Si Chum", 70},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Saphan Hin", 90},
{"Sukhothai", "Khiri Mat", "Adventure", "Ramkhamhaeng National Park (Khao Luang)", 600},
{"Sukhothai", "Si Satchanalai", "Culture", "Ban Na Ton Chan", 0},
{"Sukhothai", "Sawankhalok", "Natural", "Organic Agriculture Project, Sukhothai Airport", 0},
{"Sukhothai", "Si Satchanalai", "Culture", "Si Satchanalai Historical Park", 80},
{"Sukhothai", "Si Satchanalai", "Culture", "Wat Chang Lom", 70},
{"Sukhothai", "Si Satchanalai", "Culture", "Wat Phra Si Rattana Mahathat (Wat Phra Borommathat Mueang Chaliang)", 70},
{"Sukhothai", "Mueang Sukhothai", "Photo", "Sukhothai Marigold Field", 0},
{"Sukhothai", "Mueang Sukhothai", "Photo", "Heart-Shaped Island, Thung Thalay Luang", 0},
{"Sukhothai", "Si Satchanalai", "Photo", "Nong Lom Rice Field", 0},
{"Sukhothai", "Thung Saliam", "Culture", "Wat Phiphat Mongkhon", 0},
{"Sukhothai", "Si Satchanalai", "Adventure", "Doi Khao Mung", 50},
{"Sukhothai", "Thung Saliam", "Culture", "Wat Thung Saliam (Luang Pho Sila)", 0},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Phra Phai Luang", 70},
{"Sukhothai", "Ban Dan Lan Hoi", "Natural", "Hat Chao Ram", 0},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Phra Mae Ya Shrine", 0},
{"Sukhothai", "Mueang Sukhothai", "Photo", "Saritphong Dam (Phra Ruang Dam)", 70},
{"Sukhothai", "Si Satchanalai", "Culture", "Wat Chedi Chet Thaeo", 70},
{"Sukhothai", "Mueang Sukhothai", "Photo", "Wat Sa Si", 60},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Traphang Ngoen", 70},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Traphang Thong", 0},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Wat Si Sawai", 70},
{"Sukhothai", "Mueang Sukhothai", "Culture", "Ho Phra Phuttha Sirimara Wichai", 0},
{"Sukhothai", "Khiri Mat", "Adventure", "Pha Narai", 550},
{"Sukhothai", "Si Satchanalai", "Natural", "Huai Suang Reservoir", 0},
{"Sukhothai", "Si Satchanalai", "Photo", "Doi Daeng", 20},
{"Sukhothai", "Si Samrong", "Culture", "Wat Tham Rakhang", 0},

// --- Phitsanulok ---
{"Phitsanulok", "Nakhon Thai", "Adventure", "Phu Hin Rong Kla National Park", 90},
{"Phitsanulok", "Nakhon Thai", "Natural", "Lan Hin Pum", 70},
{"Phitsanulok", "Nakhon Thai", "Photo", "Paper Flower Field (Phu Hin Rong Kla Project)", 40},
{"Phitsanulok", "Nakhon Thai", "Natural", "Khao Pok Lon", 0},
{"Phitsanulok", "Nakhon Thai", "Natural", "Thung Salaeng Luang National Park", 0},
{"Phitsanulok", "Wang Thong", "Natural", "Kaeng Song Waterfall", 70},
{"Phitsanulok", "Wang Thong", "Adventure", "Nam Khek River Rafting", 500},
{"Phitsanulok", "Noen Maprang", "Photo", "Noen Maprang Viewpoint (Baan Suan Chom View)", 500},
{"Phitsanulok", "Noen Maprang", "Adventure", "Limestone Mountains, Boat trip to Ta Muen", 0},
{"Phitsanulok", "Noen Maprang", "Natural", "Khun Huai Thoen Waterfall", 0},
{"Phitsanulok", "Noen Maprang", "Photo", "Bat Viewpoint (Baan Mung)", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Phitsanulok City Pillar Shrine", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Phitsanulok Clock Tower", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Wat Phra Si Rattana Mahathat Woramahawihan (Wat Yai)", 20},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Wat Nang Phaya", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Wat Ratchaburana", 10},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Chan Palace", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "King Naresuan the Great Shrine", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Culture", "Wat Chan Tawan Tok", 0},
{"Phitsanulok", "Mueang Phitsanulok", "Photo", "Amornrat Lotus Garden", 20},
{"Phitsanulok", "Chat Trakan", "Natural", "Ban Rom Klao Botanic Garden", 50},
{"Phitsanulok", "Chat Trakan", "Natural", "Chat Trakan Waterfall National Park", 70},
{"Phitsanulok", "Chat Trakan", "Natural", "Tat Pla Kang Waterfall", 70},
{"Phitsanulok", "Nakhon Thai", "Adventure", "Man Daeng Waterfall", 120},
{"Phitsanulok", "Nakhon Thai", "Natural", "Kaeng Sopha Waterfall", 70},
{"Phitsanulok", "Nakhon Thai", "Natural", "Rom Klao Pharadon Waterfall", 60},
{"Phitsanulok", "Wang Thong", "Natural", "Sakunothayan Waterfall", 0},
{"Phitsanulok", "Wat Bot", "Natural", "Khwae Noi Bamrung Daen Dam", 50},
{"Phitsanulok", "Wang Thong", "Photo", "JP Farm (Mae Ra Ka Flower Field)", 40},
{"Phitsanulok", "Wang Thong", "Photo", "Street Art Wang Thong", 0},
{"Phitsanulok", "Nakhon Thai", "Natural", "Huai Sai Reservoir", 0},
{"Phitsanulok", "Nakhon Thai", "Adventure", "Rafting at Kaeng Hai", 50},

// --- Kamphaeng Phet ---
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Kamphaeng Phet Historical Park", 150},
{"Kamphaeng Phet", "Pang Sila Thong", "Adventure", "Moko Chu Peak (Mae Wong National Park)", 570},
{"Kamphaeng Phet", "Khlong Lan", "Photo", "Little Moko Chu", 70},
{"Kamphaeng Phet", "Kosamphi Nakhon", "Natural", "Khlong Wang Chao National Park", 80},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Photo", "Blue Pond (Grand Canyon Kamphaeng Phet)", 0},
{"Kamphaeng Phet", "Pang Sila Thong", "Natural", "Chong Yen (Mae Wong National Park)", 70},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Phra Si Iriyabot", 70},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Phra Borommathat Nakhon Chum", 0},
{"Kamphaeng Phet", "Khlong Lan", "Natural", "Khlong Lan Waterfall", 80},
{"Kamphaeng Phet", "Khlong Lan", "Natural", "Khlong Nam Lai Waterfall", 70},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Kamphaeng Phet City Pillar Shrine", 0},
{"Kamphaeng Phet", "Khlong Lan", "Adventure", "Tao Dam Waterfall", 470},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Phra Kaew", 20},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Chang Rop", 70},
{"Kamphaeng Phet", "Phran Kratai", "Photo", "Chakangrao Melon Farm", 0},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Khu Yang", 0},
{"Kamphaeng Phet", "Mueang Kamphaeng Phet", "Culture", "Wat Thep Moli (Luang Pho Mo)", 0},

// --- Phetchabun ---
{"Phetchabun", "Si Thep", "Culture", "Si Thep Historical Park (World Heritage)", 90},
{"Phetchabun", "Khao Kho", "Natural", "Khao Kho Sea of Mist", 50},
{"Phetchabun", "Lom Kao", "Natural", "Phu Thap Boek", 40},
{"Phetchabun", "Khao Kho", "Culture", "Wat Phra That Pha Son Kaeo", 0},
{"Phetchabun", "Mueang Phetchabun", "Culture", "Phetchabura Buddhist Park (Phra Phuttha Maha Thammaracha)", 0},
{"Phetchabun", "Khao Kho", "Adventure", "Wang Tum Waterfall", 920},
{"Phetchabun", "Khao Kho", "Natural", "Thung Salaeng Luang National Park", 70},
{"Phetchabun", "Khao Kho", "Natural", "Freshwater Jellyfish, Kaeng Bang Rachan", 100},
{"Phetchabun", "Lom Kao", "Photo", "Pha Hua Sing", 50},
{"Phetchabun", "Lom Kao", "Natural", "Phu Phaeng Ma (Phu Hin Rong Kla National Park)", 70},
{"Phetchabun", "Khao Kho", "Culture", "Kanchanaphisek Pagoda", 0},
{"Phetchabun", "Lom Sak", "Photo", "Thai Lom Walking Street", 0},
{"Phetchabun", "Khao Kho", "Natural", "Si Dit Waterfall", 50},
{"Phetchabun", "Lom Sak", "Photo", "Huai Tong Bridge (Pho Khun Pha Mueang Bridge)", 0},
{"Phetchabun", "Nam Nao", "Natural", "Nam Nao National Park", 70},
{"Phetchabun", "Wang Pong", "Natural", "Pha Khong Mountain Range (Seven-Color Cliff)", 0},
{"Phetchabun", "Khao Kho", "Photo", "Amazing Dinosaur Khao Kho", 100},

// --- Phichit ---
{"Phichit", "Mueang Phichit", "Natural", "Bueng Si Fai", 30},
{"Phichit", "Mueang Phichit", "Culture", "Phichit Old City Park", 0},
{"Phichit", "Mueang Phichit", "Photo", "Phichit Railway Station", 0},
{"Phichit", "Pho Prathap Chang", "Culture", "Wat Pho Prathap Chang", 0},
{"Phichit", "Mueang Phichit", "Culture", "Wat Tha Luang (Luang Pho Phet)", 0},
{"Phichit", "Mueang Phichit", "Culture", "Wat Khao Rup Chang", 0},
{"Phichit", "Sam Ngam", "Culture", "Wat Mai Plai Huai", 0},
{"Phichit", "Mueang Phichit", "Culture", "Wat Nakhon Chum", 0},
{"Phichit", "Mueang Phichit", "Photo", "Wang Krot Old Market", 0},
{"Phichit", "Tap Khlo", "Natural", "Giant Curcuma Field, Ban Khao Lon", 0},
{"Phichit", "Bang Mun Nak", "Culture", "Wat Sukhumaram (Large Reclining Buddha)", 0},
{"Phichit", "Sam Ngam", "Photo", "Wat Si Sattharam (Crocodile Chapel)", 0},
{"Phichit", "Mueang Phichit", "Culture", "Ho Chi Minh House Museum", 0},
{"Phichit", "Pho Thale", "Culture", "Wat Thai Nam (Luang Pho Ngoen Old Temple)", 0},

// --- Nakhon Sawan ---
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Photo", "Sawan Park (Dragon Sawan)", 40},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Natural", "Bueng Boraphet", 50},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Photo", "Pasan (Chao Phraya River Source Landmark)", 40},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Wat Si Uthumphon (Wat Luang Pho Choi)", 0},
{"Nakhon Sawan", "Takhli", "Culture", "Chao Pho Nakhon Ratch Shrine", 0},
{"Nakhon Sawan", "Takhli", "Culture", "Wat Chan Sen (Chan Sen Museum)", 0},
{"Nakhon Sawan", "Banphot Phisai", "Natural", "Khao No", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Photo", "Army Engineer Sheep Farm", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Wat Khiriwong (Phra Chulamani Pagoda)", 0},
{"Nakhon Sawan", "Tha Tako", "Culture", "Wat Pa Siri Watthana Wisut", 30},
{"Nakhon Sawan", "Chum Saeng", "Photo", "Chum Saeng 100-Year Market", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Photo", "Nakhon Sawan Observation Tower", 20},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Chao Pho Thepharak & Chao Mae Thapthim Shrine", 0},
{"Nakhon Sawan", "Chum Saeng", "Culture", "Wat Khoe Chai Nuea (Borommathat)", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Natural", "Wat Thep Nimit Songtham (Tham Bo Ya)", 0},
{"Nakhon Sawan", "Chum Saeng", "Photo", "Hiran Narumit Bridge", 0},
{"Nakhon Sawan", "Takhli", "Culture", "Luang Pho Doem Museum, Wat Nong Pho", 40},
{"Nakhon Sawan", "Mae Poen", "Natural", "Khlong Pho Dam", 40},
{"Nakhon Sawan", "Chum Ta Bong", "Natural", "Thung Hin Thoen", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Wat Woranat Banphot (Wat Khao Kop)", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Ganesha Park", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Nakhon Sawan City Pillar Shrine", 0},
{"Nakhon Sawan", "Tak Fa", "Photo", "Pao Tung Farm", 40},
{"Nakhon Sawan", "Kao Liao", "Culture", "Wat Makkhara Rangsalit (Wat Takhro)", 0},
{"Nakhon Sawan", "Takhli", "Culture", "Wat Khao Phu Kha Chulamani", 0},
{"Nakhon Sawan", "Kao Liao", "Culture", "Wat Khao Din Tai (Wat Phra No Thoranin)", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Photo", "Wat Khlong Khang Pier Market", 0},
{"Nakhon Sawan", "Mueang Nakhon Sawan", "Culture", "Nakhon Sawan Royal Monastery", 0},
{"Nakhon Sawan", "Banphot Phisai", "Culture", "Dong Mae Nang Mueang Ancient City", 0},
{"Nakhon Sawan", "Phayuha Khiri", "Culture", "Wat Sa Thale", 0},

// --- Uthai Thani ---
{"Uthai Thani", "Mueang Uthai Thani", "Culture", "Wat Chantharam (Wat Tha Sung)", 0},
{"Uthai Thani", "Mueang Uthai Thani", "Culture", "Khao Sakae Krang (Wat Sangkat Rattana Khiri)", 0},
{"Uthai Thani", "Mueang Uthai Thani", "Culture", "Wat Uposatharam (Wat Bot)", 0},
{"Uthai Thani", "Lan Sak", "Natural", "Hup Pa Tat", 20},
{"Uthai Thani", "Lan Sak", "Natural", "Huai Kha Khaeng Wildlife Sanctuary (World Heritage)", 50},
{"Uthai Thani", "Ban Rai", "Culture", "Wat Pha Thang (Large Luang Pho To Statue)", 0},
{"Uthai Thani", "Ban Rai", "Natural", "Pha Rom Yen Waterfall", 0},
{"Uthai Thani", "Ban Rai", "Natural", "Tham Phu Wai", 20},
{"Uthai Thani", "Ban Rai", "Culture", "Wat Tham Khao Wong", 0},
{"Uthai Thani", "Mueang Uthai Thani", "Photo", "Sakae Krang River Cruise", 50},
{"Uthai Thani", "Mueang Uthai Thani", "Photo", "Trok Rong Ya (Old Ban Sakae Krang Market)", 0},
{"Uthai Thani", "Ban Rai", "Photo", "Pang Sawan Weir", 0},
{"Uthai Thani", "Ban Rai", "Culture", "Ban Pha Thang Ancient Textile Center", 0},
{"Uthai Thani", "Ban Rai", "Natural", "Giant Tree (Ban Sa Nam)", 0},
{"Uthai Thani", "Lan Sak", "Photo", "Ban Chai Khao Viewpoint (Switzerland of Thailand)", 0},
{"Uthai Thani", "Ban Rai", "Photo", "Sao Hai Market", 0},
{"Uthai Thani", "Mueang Uthai Thani", "Photo", "Ko Thepho Suspension Bridge", 0}
};
struct restaurant {
    
    string district;
    string type;
    string name;
    int price;
};
vector<restaurant>allrestaurant = {

   {"Mueang Chiang Mai", "Noodle", "ข้าวซอยแม่สาย", 50},
{"Mueang Chiang Mai", "Noodle", "ก๋วยเตี๋ยวอัญชัน", 60},
{"Mueang Chiang Mai", "Noodle", "ขนมจีนสันป่าข่อย", 40},
{"Mueang Chiang Mai", "Noodle", "ก๋วยเตี๋ยวเนื้อท่าน้ำ", 80},
{"Mueang Chiang Mai", "Noodle", "บะหมี่เฮียเม้ง", 55},
{"Mueang Chiang Mai", "Rice", "ข้าวขาหมูช้างเผือก", 60},
{"Mueang Chiang Mai", "Rice", "ไก่เกียรติโอชา", 60},
{"Mueang Chiang Mai", "Rice", "ข้าวแกงลุงไทย", 45},
{"Mueang Chiang Mai", "Rice", "ข้าวหมูแดงสีมงคล", 50},
{"Mueang Chiang Mai", "Rice", "ข้าวผัดปู ป.ประทีป", 80},

// --- Chom Thong ---
{"Chom Thong", "Noodle", "ก๋วยเตี๋ยวต้มยำดอยอินทนนท์", 50},
{"Chom Thong", "Noodle", "ข้าวซอยป้าสายจอมทอง", 45},
{"Chom Thong", "Noodle", "ขนมจีนน้ำย้อยเมืองเหนือ", 40},
{"Chom Thong", "Noodle", "หมี่เหลืองผัดไทยกาดนัด", 50},
{"Chom Thong", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นศิลา", 60},
{"Chom Thong", "Rice", "ข้าวหมูแดงจอมทองโบราณ", 50},
{"Chom Thong", "Rice", "ข้าวมันไก่สวนรุกขชาติ", 45},
{"Chom Thong", "Rice", "ข้าวขาหมูยอดดอย", 60},
{"Chom Thong", "Rice", "ลาบคั่วข้าวเหนียวร้อน", 80},
{"Chom Thong", "Rice", "ข้าวแกงปักษ์ใต้คนเมือง", 40},

// --- Mae Rim ---
{"Mae Rim", "Noodle", "ก๋วยเตี๋ยวเรือแม่ริม", 50},
{"Mae Rim", "Noodle", "ข้าวซอยไก่ฟ้าแม่ริม", 60},
{"Mae Rim", "Noodle", "บะหมี่เกี๊ยวทำเองแม่ริม", 55},
{"Mae Rim", "Noodle", "ก๋วยเตี๋ยวปลาชมสวน", 70},
{"Mae Rim", "Noodle", "ขนมจีนน้ำเงี้ยวป้าคำ", 40},
{"Mae Rim", "Rice", "ข้าวมันไก่แม่ริมเจ้าเก่า", 50},
{"Mae Rim", "Rice", "ข้าวขาหมูเหมืองแก้ว", 60},
{"Mae Rim", "Rice", "ครัวบ้านทุ่งตามสั่ง", 80},
{"Mae Rim", "Rice", "ข้าวซอยเนื้อน่องลายเสิร์ฟพร้อมข้าว", 90},
{"Mae Rim", "Rice", "ข้าวผัดน้ำพริกหนุ่มแม่ริม", 70},

// --- Hang Dong ---
{"Hang Dong", "Noodle", "ก๋วยเตี๋ยวห้อยขาหางดง", 50},
{"Hang Dong", "Noodle", "ข้าวซอยลุงรวย", 55},
{"Hang Dong", "Noodle", "บะหมี่เป็ดตุ๋นหางดง", 70},
{"Hang Dong", "Noodle", "ก๋วยเตี๋ยวเรืออยุธยาหางดง", 45},
{"Hang Dong", "Noodle", "เย็นตาโฟเครื่องทรงหางดง", 60},
{"Hang Dong", "Rice", "ข้าวมันไก่สองพี่น้อง", 50},
{"Hang Dong", "Rice", "ข้าวหมูทอดน้ำปลาหางดง", 55},
{"Hang Dong", "Rice", "ข้าวหน้าเป็ดหย่างฮ่องเต้", 85},
{"Hang Dong", "Rice", "ครัวหางดงอาหารตามสั่ง", 50},
{"Hang Dong", "Rice", "ข้าวคลุกกะปิคุณย่า", 65},

// --- Chiang Dao ---
{"Chiang Dao", "Noodle", "ก๋วยเตี๋ยวเรือเชียงดาว", 50},
{"Chiang Dao", "Noodle", "ข้าวซอยป้าแก้วเชียงดาว", 55},
{"Chiang Dao", "Noodle", "บะหมี่หมูแดงเชียงดาว", 50},
{"Chiang Dao", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นยาจีนเชียงดาว", 60},
{"Chiang Dao", "Noodle", "ขนมจีนน้ำเงี้ยวเชียงดาวเจ้าเก่า", 40},
{"Chiang Dao", "Rice", "ข้าวขาหมูเชียงดาวเจ้าดัง", 60},
{"Chiang Dao", "Rice", "ข้าวมันไก่ตอนเชียงดาว", 50},
{"Chiang Dao", "Rice", "ครัวเชียงดาวอาหารป่า", 120},
{"Chiang Dao", "Rice", "ข้าวหน้าหมูกรอบเชียงดาว", 65},
{"Chiang Dao", "Rice", "ข้าวราดพริกแกงดอยหลวง", 70},

// --- Mae Taeng ---
{"Mae Taeng", "Noodle", "ก๋วยเตี๋ยวเรือแม่แตง", 50},
{"Mae Taeng", "Noodle", "ข้าวซอยเนื้อแม่แตง", 65},
{"Mae Taeng", "Noodle", "บะหมี่เกี๊ยวหมูแดงแม่แตง", 50},
{"Mae Taeng", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่หวานแม่แตง", 60},
{"Mae Taeng", "Noodle", "ผัดไทยกุ้งสดแม่แตง", 70},
{"Mae Taeng", "Rice", "ข้าวมันไก่ตอนแม่แตง", 50},
{"Mae Taeng", "Rice", "ข้าวขาหมูแม่แตงรสเด็ด", 60},
{"Mae Taeng", "Rice", "ครัวริมทางแม่แตง", 55},
{"Mae Taeng", "Rice", "ข้าวผัดกระเพราถาดแม่แตง", 80},
{"Mae Taeng", "Rice", "ข้าวหมูทอดแม่แตง", 50},

// --- Samoeng ---
{"Samoeng", "Noodle", "ก๋วยเตี๋ยวต้มยำสตรอว์เบอร์รีสะเมิง", 60},
{"Samoeng", "Noodle", "ข้าวซอยไก่สะเมิง", 50},
{"Samoeng", "Noodle", "บะหมี่น้ำหมูแดงสะเมิง", 50},
{"Samoeng", "Noodle", "ขนมจีนน้ำเงี้ยวสะเมิงโบราณ", 40},
{"Samoeng", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกสะเมิง", 45},
{"Samoeng", "Rice", "ข้าวมันไก่สะเมิงดอย", 50},
{"Samoeng", "Rice", "ข้าวขาหมูสะเมิงรสเด็ด", 60},
{"Samoeng", "Rice", "ข้าวราดลาบคั่วสะเมิง", 70},
{"Samoeng", "Rice", "ครัวสะเมิงตามสั่ง", 50},
{"Samoeng", "Rice", "ข้าวเหนียวหมูปิ้งสะเมิง", 45},

// --- Mueang Chiang Rai ---
{"Mueang Chiang Rai", "Noodle", "น้ำเงี้ยวป้าสุข", 40},
{"Mueang Chiang Rai", "Noodle", "ข้าวซอยพอใจ", 50},
{"Mueang Chiang Rai", "Noodle", "ก๋วยเตี๋ยวเรือสหชัย", 50},
{"Mueang Chiang Rai", "Noodle", "บะหมี่เกี๊ยวเฮียเม้ง", 50},
{"Mueang Chiang Rai", "Noodle", "ขนมจีนน้ำยาป้าอ๊อด", 40},
{"Mueang Chiang Rai", "Rice", "ข้าวต้มมีนา", 50},
{"Mueang Chiang Rai", "Rice", "ข้าวมันไก่นครปฐม (เชียงราย)", 50},
{"Mueang Chiang Rai", "Rice", "ลาบสนามบิน", 120},
{"Mueang Chiang Rai", "Rice", "ข้าวหมูแดงเจ๊หวัง", 55},
{"Mueang Chiang Rai", "Rice", "ครัวศิลปิน (ตามสั่ง)", 80},

// --- Mae Suai ---
{"Mae Suai", "Noodle", "ก๋วยเตี๋ยวเนื้อดอยช้าง", 80},
{"Mae Suai", "Noodle", "ข้าวซอยไก่แม่สรวย", 50},
{"Mae Suai", "Noodle", "บะหมี่หมูย่างแม่สรวย", 55},
{"Mae Suai", "Noodle", "เส้นเล็กต้มยำดอยวาวี", 50},
{"Mae Suai", "Noodle", "ผัดไทยเขื่อนแม่สรวย", 60},
{"Mae Suai", "Rice", "ข้าวผัดดอยช้าง", 90},
{"Mae Suai", "Rice", "ข้าวมันไก่แม่สรวยเจ้าเก่า", 45},
{"Mae Suai", "Rice", "ข้าวขาหมูแม่สรวยรสเด็ด", 60},
{"Mae Suai", "Rice", "ลาบหมูคั่วแม่สรวย", 80},
{"Mae Suai", "Rice", "ครัวริมทางตามสั่ง", 50},

// --- Mae Sai ---
{"Mae Sai", "Noodle", "ข้าวซอยน้อยแม่สาย", 40},
{"Mae Sai", "Noodle", "ก๋วยเตี๋ยวปลาแม่สาย", 60},
{"Mae Sai", "Noodle", "ขนมจีนน้ำเงี้ยวแม่สายโบราณ", 45},
{"Mae Sai", "Noodle", "บะหมี่ไทยใหญ่", 50},
{"Mae Sai", "Noodle", "เส้นหมี่ต้มยำชายแดน", 50},
{"Mae Sai", "Rice", "ข้าวฟืนอุ่นแม่สาย", 40},
{"Mae Sai", "Rice", "ข้าวมันไก่ตอนแม่สาย", 50},
{"Mae Sai", "Rice", "ข้าวหน้าเป็ดแม่สาย", 70},
{"Mae Sai", "Rice", "ข้าวขาหมูเจ๊จูแม่สาย", 60},
{"Mae Sai", "Rice", "ครัวแม่สายอาหารตามสั่ง", 55},

// --- Thoeng ---
{"Thoeng", "Noodle", "ก๋วยเตี๋ยวเรือเทิง", 45},
{"Thoeng", "Noodle", "ข้าวซอยเนื้อเทิง", 60},
{"Thoeng", "Noodle", "บะหมี่เกี๊ยวเทิงรสเด็ด", 50},
{"Thoeng", "Noodle", "เส้นเล็กน้ำใสภูชี้ฟ้า", 50},
{"Thoeng", "Noodle", "เย็นตาโฟเครื่องทรงเทิง", 55},
{"Thoeng", "Rice", "ข้าวมันไก่เทิงเจ้าเก่า", 45},
{"Thoeng", "Rice", "ข้าวขาหมูเทิงรสเด็ด", 55},
{"Thoeng", "Rice", "ลาบปลาคังเทิง", 100},
{"Thoeng", "Rice", "ข้าวผัดกระเพราเทิงถาด", 70},
{"Thoeng", "Rice", "ครัวเทิงอาหารป่า", 90},

// --- Wiang Kaen ---
{"Wiang Kaen", "Noodle", "ก๋วยเตี๋ยวหมูเวียงแก่น", 45},
{"Wiang Kaen", "Noodle", "ข้าวซอยไก่ยูนนาน", 60},
{"Wiang Kaen", "Noodle", "บะหมี่น้ำเวียงแก่น", 45},
{"Wiang Kaen", "Noodle", "เส้นเล็กต้มยำผาตั้ง", 50},
{"Wiang Kaen", "Noodle", "ขนมจีนน้ำเงี้ยวเวียงแก่น", 40},
{"Wiang Kaen", "Rice", "ข้าวผัดยูนนาน", 80},
{"Wiang Kaen", "Rice", "ข้าวมันไก่เวียงแก่น", 50},
{"Wiang Kaen", "Rice", "ขาหมูหมั่นโถวผาตั้ง", 150},
{"Wiang Kaen", "Rice", "ข้าวราดคะน้าหมูกรอบ", 60},
{"Wiang Kaen", "Rice", "ลาบไก่เวียงแก่น", 80},

// --- Mae Fa Luang ---
{"Mae Fa Luang", "Noodle", "บะหมี่ยูนนานแม่สลอง", 60},
{"Mae Fa Luang", "Noodle", "ข้าวซอยเนื้อแม่สลอง", 70},
{"Mae Fa Luang", "Noodle", "ก๋วยเตี๋ยวไก่ดำยาจีน", 90},
{"Mae Fa Luang", "Noodle", "บะหมี่แห้งซอสยูนนาน", 60},
{"Mae Fa Luang", "Noodle", "เส้นหมี่น้ำใสแม่ฟ้าหลวง", 50},
{"Mae Fa Luang", "Rice", "ขาหมูหมั่นโถวดอยแม่สลอง", 200},
{"Mae Fa Luang", "Rice", "ข้าวมันไก่ดำ", 120},
{"Mae Fa Luang", "Rice", "ข้าวผัดชาอูหลง", 80},
{"Mae Fa Luang", "Rice", "ข้าวราดหมูผัดเห็ดหอมสด", 90},
{"Mae Fa Luang", "Rice", "ลาบหมูยูนนาน", 100},

// --- Chiang Saen ---
{"Chiang Saen", "Noodle", "ก๋วยเตี๋ยวเรือเชียงแสน", 40},
{"Chiang Saen", "Noodle", "ข้าวซอยไก่เชียงแสน", 50},
{"Chiang Saen", "Noodle", "บะหมี่เป็ดเชียงแสน", 70},
{"Chiang Saen", "Noodle", "เส้นเล็กต้มยำริมโขง", 50},
{"Chiang Saen", "Noodle", "ขนมจีนน้ำเงี้ยวเชียงแสน", 40},
{"Chiang Saen", "Rice", "ข้าวมันไก่เชียงแสนเจ้าเก่า", 50},
{"Chiang Saen", "Rice", "ข้าวขาหมูเชียงแสนรสเด็ด", 60},
{"Chiang Saen", "Rice", "ลาบปลาคังแม่น้ำโขง", 150},
{"Chiang Saen", "Rice", "ข้าวผัดต้มยำทะเลโขง", 80},
{"Chiang Saen", "Rice", "ข้าวราดพริกแกงปลาคัง", 90},

// --- Mae Chan ---
{"Mae Chan", "Noodle", "ก๋วยเตี๋ยวหมูแม่จัน", 45},
{"Mae Chan", "Noodle", "ข้าวซอยป้าคำแม่จัน", 50},
{"Mae Chan", "Noodle", "บะหมี่เกี๊ยวแม่จันรสเด็ด", 50},
{"Mae Chan", "Noodle", "เย็นตาโฟแม่จัน", 50},
{"Mae Chan", "Noodle", "เส้นเล็กน้ำใสแม่จัน", 45},
{"Mae Chan", "Rice", "ข้าวมันไก่ตอนแม่จัน", 50},
{"Mae Chan", "Rice", "ข้าวขาหมูแม่จันเจ้าเก่า", 60},
{"Mae Chan", "Rice", "ข้าวหน้าเป็ดแม่จัน", 70},
{"Mae Chan", "Rice", "ลาบหมูคั่วแม่จัน", 80},
{"Mae Chan", "Rice", "ครัวแม่จันตามสั่ง", 55},

// --- Mueang Mae Hong Son ---
{"Mueang Mae Hong Son", "Noodle", "ก๋วยเตี๋ยวบ้านไม้", 50},
{"Mueang Mae Hong Son", "Noodle", "ข้าวซอยป้าหอม", 55},
{"Mueang Mae Hong Son", "Noodle", "ขนมจีนน้ำเงี้ยวป้าสุข", 40},
{"Mueang Mae Hong Son", "Noodle", "บะหมี่เกี๊ยวทำเองกาดเก่า", 50},
{"Mueang Mae Hong Son", "Noodle", "เส้นเล็กต้มยำปลาคัง", 70},
{"Mueang Mae Hong Son", "Rice", "ข้าวเหลืองหน้าไก่ (อาหารไทใหญ่)", 50},
{"Mueang Mae Hong Son", "Rice", "ข้าวมันไก่ปางล้อ", 50},
{"Mueang Mae Hong Son", "Rice", "ข้าวขาหมูแม่ฮ่องสอนรสเด็ด", 60},
{"Mueang Mae Hong Son", "Rice", "ใบเฟิร์น (อาหารพื้นเมือง/ข้าว)", 180},
{"Mueang Mae Hong Son", "Rice", "ข้าวผัดสับปะรดภูเขาสูง", 80},

// --- Khun Yuam ---
{"Khun Yuam", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นขุนยวม", 50},
{"Khun Yuam", "Noodle", "ข้าวซอยน่องไก่บัวตอง", 60},
{"Khun Yuam", "Noodle", "บะหมี่น้ำใสขุนยวม", 45},
{"Khun Yuam", "Noodle", "เส้นหมี่ราดหน้ายอดผัก", 55},
{"Khun Yuam", "Noodle", "ขนมจีนน้ำยากะทิป้าหวัง", 40},
{"Khun Yuam", "Rice", "ข้าวมันไก่ขุนยวมเจ้าเก่า", 50},
{"Khun Yuam", "Rice", "ข้าวขาหมูทุ่งบัวตอง", 60},
{"Khun Yuam", "Rice", "ข้าวหน้าเป็ดขุนยวม", 70},
{"Khun Yuam", "Rice", "ครัวขุนยวมตามสั่ง", 55},
{"Khun Yuam", "Rice", "ลาบไก่ขุนยวมเสิร์ฟพร้อมข้าว", 80},

// --- Pang Mapha ---
{"Pang Mapha", "Noodle", "ก๋วยเตี๋ยวห้อยขาถ้ำลอด", 50},
{"Pang Mapha", "Noodle", "ข้าวซอยไทยใหญ่ปางมะผ้า", 55},
{"Pang Mapha", "Noodle", "บะหมี่น้ำหมูแดงปางมะผ้า", 50},
{"Pang Mapha", "Noodle", "เส้นเล็กต้มยำน้ำข้น", 55},
{"Pang Mapha", "Noodle", "ก๋วยเตี๋ยวเป็ดตุ๋นปางมะผ้า", 70},
{"Pang Mapha", "Rice", "ข้าวผัดชาวดอย", 70},
{"Pang Mapha", "Rice", "ข้าวมันไก่ปางมะผ้ารสเด็ด", 50},
{"Pang Mapha", "Rice", "ข้าวขาหมูสูตรโบราณ", 60},
{"Pang Mapha", "Rice", "ครัวนกน้อย (ตามสั่ง)", 55},
{"Pang Mapha", "Rice", "ข้าวหน้าหมูกรอบถ้ำลอด", 65},

// --- Pai ---
{"Pai", "Noodle", "ข้าวซอยน้องเบียร์", 60},
{"Pai", "Noodle", "ขนมจีนน้ำเงี้ยวป้าหยิน", 40},
{"Pai", "Noodle", "ก๋วยเตี๋ยวเรือท่าน้ำปาย", 50},
{"Pai", "Noodle", "ผัดไทยหน้าอำเภอปาย", 60},
{"Pai", "Noodle", "บะหมี่ยูนนานหมู่บ้านสันติชล", 70},
{"Pai", "Rice", "ข้าวมันไก่ตอนปาย", 50},
{"Pai", "Rice", "ขาหมูหมั่นโถวสันติชล", 180},
{"Pai", "Rice", "ข้าวหมกไก่ฮาลาลปาย", 60},
{"Pai", "Rice", "ครัวระเบียงปาย (ตามสั่ง)", 120},
{"Pai", "Rice", "ข้าวราดคะน้าหมูกรอบปาย", 65},

// --- Mueang Lamphun ---
{"Mueang Lamphun", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นลำไย", 55},
{"Mueang Lamphun", "Noodle", "ข้าวซอยวิงยอง", 50},
{"Mueang Lamphun", "Noodle", "บะหมี่โกจือ", 50},
{"Mueang Lamphun", "Noodle", "ขนมจีนประตูลี้", 40},
{"Mueang Lamphun", "Noodle", "เส้นเล็กต้มยำนครหริภุญชัย", 50},
{"Mueang Lamphun", "Rice", "ข้าวมันไก่หริภุญชัย", 50},
{"Mueang Lamphun", "Rice", "ข้าวขาหมูหน้าวัดพระธาตุ", 60},
{"Mueang Lamphun", "Rice", "ดาวคะนอง (อาหารพื้นเมือง/ข้าว)", 150},
{"Mueang Lamphun", "Rice", "ข้าวแกงป้าต้อยลำพูน", 40},
{"Mueang Lamphun", "Rice", "ข้าวหน้าหมูทอดลำพูน", 55},

// --- Li ---
{"Li", "Noodle", "ก๋วยเตี๋ยวเรือเมืองลี้", 45},
{"Li", "Noodle", "ข้าวซอยไก่เมืองลี้", 50},
{"Li", "Noodle", "บะหมี่น้ำใสป้าคำ", 45},
{"Li", "Noodle", "เย็นตาโฟเทศบาลลี้", 50},
{"Li", "Noodle", "เส้นหมี่ราดหน้าเนื้อนุ่ม", 55},
{"Li", "Rice", "ข้าวมันไก่ลี้เจ้าเก่า", 45},
{"Li", "Rice", "ข้าวขาหมูเมืองลี้รสเด็ด", 55},
{"Li", "Rice", "ครัวเมืองลี้อาหารตามสั่ง", 50},
{"Li", "Rice", "ข้าวผัดน้ำพริกตาแดงลี้", 65},
{"Li", "Rice", "ลาบขมเมืองลี้เสิร์ฟพร้อมข้าว", 80},

// --- Thung Hua Chang ---
{"Thung Hua Chang", "Noodle", "ก๋วยเตี๋ยวหมูทุ่งหัวช้าง", 40},
{"Thung Hua Chang", "Noodle", "ข้าวซอยเนื้อทุ่งหัวช้าง", 60},
{"Thung Hua Chang", "Noodle", "บะหมี่แห้งหมูแดง", 45},
{"Thung Hua Chang", "Noodle", "ขนมจีนน้ำยากะทิป้าหวัง", 40},
{"Thung Hua Chang", "Noodle", "ก๋วยเตี๋ยวเป็ดทุ่งหัวช้าง", 65},
{"Thung Hua Chang", "Rice", "ข้าวมันไก่ตอนทุ่งหัวช้าง", 50},
{"Thung Hua Chang", "Rice", "ข้าวขาหมูสูตรโบราณ", 55},
{"Thung Hua Chang", "Rice", "ครัวบ้านสวนตามสั่ง", 50},
{"Thung Hua Chang", "Rice", "ข้าวหน้าไก่ทอดกรอบ", 55},
{"Thung Hua Chang", "Rice", "ข้าวราดพริกแกงหมูป่า", 70},

// --- Mae Tha --- (Lamphun)
{"Mae Tha", "Noodle", "ก๋วยเตี๋ยวต้มยำริมทางแม่ทา", 50},
{"Mae Tha", "Noodle", "ข้าวซอยน่องไก่แม่ทา", 55},
{"Mae Tha", "Noodle", "บะหมี่เกี๊ยวแม่ทารสเด็ด", 50},
{"Mae Tha", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Mae Tha", "Noodle", "ผัดไทยแม่ทาโบราณ", 60},
{"Mae Tha", "Rice", "ข้าวมันไก่แม่ทาเจ้าเก่า", 50},
{"Mae Tha", "Rice", "ข้าวขาหมูแม่ทารสเด็ด", 60},
{"Mae Tha", "Rice", "ครัวไม้แกะสลักแม่ทา", 100},
{"Mae Tha", "Rice", "ข้าวแกงถุงใหญ่แม่ทา", 40},
{"Mae Tha", "Rice", "ข้าวหน้าหมูกรอบแม่ทา", 65},

// --- Pa Sang ---
{"Pa Sang", "Noodle", "ก๋วยเตี๋ยวเรือป่าซาง", 45},
{"Pa Sang", "Noodle", "ข้าวซอยไก่ป่าซางโบราณ", 50},
{"Pa Sang", "Noodle", "บะหมี่หมูทอดป่าซาง", 55},
{"Pa Sang", "Noodle", "ขนมจีนน้ำเงี้ยวป่าซาง", 40},
{"Pa Sang", "Noodle", "เย็นตาโฟทรงเครื่องป่าซาง", 50},
{"Pa Sang", "Rice", "ข้าวมันไก่ป่าซางรสเด็ด", 50},
{"Pa Sang", "Rice", "ข้าวขาหมูเจ๊จู", 60},
{"Pa Sang", "Rice", "ครัวผ้าฝ้ายป่าซาง", 90},
{"Pa Sang", "Rice", "ข้าวราดคะน้าหมูกรอบป่าซาง", 60},
{"Pa Sang", "Rice", "ลาบปลาป่าซางเสิร์ฟพร้อมข้าว", 80},

// --- Mueang Phayao ---
{"Mueang Phayao", "Noodle", "ก๋วยเตี๋ยวอันเจียร (ลูกชิ้นเนื้อ)", 60},
{"Mueang Phayao", "Noodle", "ข้าวซอยแสงเพียร", 50},
{"Mueang Phayao", "Noodle", "บะหมี่น้ำใสโกเพียว", 50},
{"Mueang Phayao", "Noodle", "ขนมจีนน้ำย้อยริมกว๊าน", 45},
{"Mueang Phayao", "Noodle", "เย็นตาโฟท่ากว๊าน", 55},
{"Mueang Phayao", "Rice", "ข้าวมันไก่นันทาราม", 50},
{"Mueang Phayao", "Rice", "ข้าวขาหมูหน้าวัดศรีโคมคำ", 60},
{"Mueang Phayao", "Rice", "ครัวออโรร่า (อาหารตามสั่ง)", 120},
{"Mueang Phayao", "Rice", "ข้าวผัดน้ำพริกตาแดงปลาแห้ง", 75},
{"Mueang Phayao", "Rice", "ลาบกว๊านพะเยาเสิร์ฟพร้อมข้าว", 100},

// --- Chiang Kham ---
{"Chiang Kham", "Noodle", "ก๋วยเตี๋ยวต้มยำไทลื้อ", 50},
{"Chiang Kham", "Noodle", "ข้าวซอยไก่เชียงคำ", 50},
{"Chiang Kham", "Noodle", "บะหมี่เกี๊ยวทำเองเชียงคำ", 55},
{"Chiang Kham", "Noodle", "ขนมจีนน้ำเงี้ยวเชียงคำเจ้าเก่า", 40},
{"Chiang Kham", "Noodle", "เส้นหมี่ราดหน้าปลากะพง", 80},
{"Chiang Kham", "Rice", "ข้าวมันไก่เชียงคำรสเด็ด", 50},
{"Chiang Kham", "Rice", "ข้าวขาหมูเชียงคำสูตรโบราณ", 60},
{"Chiang Kham", "Rice", "ข้าวราดลาบหมูไทลื้อ", 70},
{"Chiang Kham", "Rice", "ครัวเชียงคำอาหารตามสั่ง", 55},
{"Chiang Kham", "Rice", "ข้าวหน้าเป็ดย่างเชียงคำ", 75},

// --- Pong ---
{"Pong", "Noodle", "ก๋วยเตี๋ยวเรืออำเภอปง", 45},
{"Pong", "Noodle", "ข้าวซอยน่องไก่ปง", 55},
{"Pong", "Noodle", "บะหมี่น้ำหมูแดงปง", 50},
{"Pong", "Noodle", "ก๋วยเตี๋ยวเนื้อตุ๋นปง", 70},
{"Pong", "Noodle", "เส้นเล็กต้มยำน้ำข้นปง", 50},
{"Pong", "Rice", "ข้าวมันไก่ปงเจ้าเก่า", 45},
{"Pong", "Rice", "ข้าวขาหมูปงรสเด็ด", 55},
{"Pong", "Rice", "ลาบปลาคังปงเสิร์ฟพร้อมข้าว", 90},
{"Pong", "Rice", "ครัวเมืองปงตามสั่ง", 50},
{"Pong", "Rice", "ข้าวหน้าหมูกรอบปง", 65},

// --- Phu Sang ---
{"Phu Sang", "Noodle", "ก๋วยเตี๋ยวริมน้ำตกภูซาง", 55},
{"Phu Sang", "Noodle", "ข้าวซอยป้าคำภูซาง", 50},
{"Phu Sang", "Noodle", "บะหมี่หมูทอดภูซาง", 55},
{"Phu Sang", "Noodle", "ขนมจีนน้ำเงี้ยวภูซาง", 40},
{"Phu Sang", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นปลา", 45},
{"Phu Sang", "Rice", "ข้าวมันไก่ภูซางรสเด็ด", 50},
{"Phu Sang", "Rice", "ข้าวขาหมูภูซางสูตรโบราณ", 60},
{"Phu Sang", "Rice", "ลาบไก่ภูซางพร้อมข้าวเหนียว", 80},
{"Phu Sang", "Rice", "ครัวชายแดนอาหารตามสั่ง", 60},
{"Phu Sang", "Rice", "ข้าวราดพริกแกงหมูป่าภูซาง", 75},

// --- Chiang Muan ---
{"Chiang Muan", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นเชียงม่วน", 50},
{"Chiang Muan", "Noodle", "ข้าวซอยเนื้อเชียงม่วน", 65},
{"Chiang Muan", "Noodle", "บะหมี่เกี๊ยวเชียงม่วนรสเด็ด", 50},
{"Chiang Muan", "Noodle", "ขนมจีนน้ำยากะทิเชียงม่วน", 45},
{"Chiang Muan", "Noodle", "ผัดไทยเชียงม่วนโบราณ", 55},
{"Chiang Muan", "Rice", "ข้าวมันไก่ตอนเชียงม่วน", 50},
{"Chiang Muan", "Rice", "ข้าวขาหมูเชียงม่วนเจ้าเก่า", 60},
{"Chiang Muan", "Rice", "ครัวฝั่งโขง (ตามสั่ง)", 80},
{"Chiang Muan", "Rice", "ข้าวราดคะน้าหมูกรอบเชียงม่วน", 60},
{"Chiang Muan", "Rice", "ข้าวหน้าหมูแดงเชียงม่วน", 55},

// --- Mae Chai ---
{"Mae Chai", "Noodle", "ก๋วยเตี๋ยวเรือแม่ใจ", 45},
{"Mae Chai", "Noodle", "ข้าวซอยไก่แม่ใจรสเด็ด", 50},
{"Mae Chai", "Noodle", "บะหมี่หมูแดงกาดแม่ใจ", 45},
{"Mae Chai", "Noodle", "ก๋วยเตี๋ยวเนื้อน้ำตกแม่ใจ", 60},
{"Mae Chai", "Noodle", "ขนมจีนน้ำเงี้ยวแม่ใจโบราณ", 40},
{"Mae Chai", "Rice", "ข้าวมันไก่แม่ใจเจ้าเก่า", 50},
{"Mae Chai", "Rice", "ข้าวขาหมูแม่ใจรสเด็ด", 60},
{"Mae Chai", "Rice", "ลาบปลาแม่ใจพร้อมข้าว", 90},
{"Mae Chai", "Rice", "ครัวแม่ใจอาหารตามสั่ง", 55},
{"Mae Chai", "Rice", "ข้าวหน้าเป็ดแม่ใจ", 70},

// --- Mueang Lampang ---
{"Mueang Lampang", "Noodle", "ก๋วยเตี๋ยวลูกชิ้นยักษ์ลำปาง", 60},
{"Mueang Lampang", "Noodle", "ข้าวซอยอิสลามลำปาง", 50},
{"Mueang Lampang", "Noodle", "บะหมี่โกจือ (เจ้าเก่า)", 50},
{"Mueang Lampang", "Noodle", "ก๋วยเตี๋ยวเรือกองต้า", 50},
{"Mueang Lampang", "Noodle", "ขนมจีนป้าปง", 40},
{"Mueang Lampang", "Rice", "ข้าวหมูแดงห้าแยก", 50},
{"Mueang Lampang", "Rice", "ข้าวมันไก่สถานีรถไฟ", 50},
{"Mueang Lampang", "Rice", "อร่อยบาทเดียว (ข้าวต้ม/ข้าวสวย)", 60},
{"Mueang Lampang", "Rice", "ข้าวขาหมูทุ่งเล้ง", 55},
{"Mueang Lampang", "Rice", "ครัวลำปางหนา (ตามสั่ง)", 120},

// --- Ko Kha ---
{"Ko Kha", "Noodle", "ก๋วยเตี๋ยวเนื้อตุ๋นเกาะคา", 60},
{"Ko Kha", "Noodle", "ข้าวซอยน่องไก่เกาะคา", 50},
{"Ko Kha", "Noodle", "บะหมี่หมูแดงเกาะคารสเด็ด", 45},
{"Ko Kha", "Noodle", "ก๋วยเตี๋ยวไทยโบราณเกาะคา", 45},
{"Ko Kha", "Noodle", "ผัดไทยกุ้งสดหน้าวัดพระธาตุ", 70},
{"Ko Kha", "Rice", "ข้าวมันไก่เกาะคาเจ้าเก่า", 45},
{"Ko Kha", "Rice", "ข้าวขาหมูเกาะคาสูตรโบราณ", 55},
{"Ko Kha", "Rice", "ลาบหมูคั่วเกาะคาพร้อมข้าว", 80},
{"Ko Kha", "Rice", "ครัวริมทางเกาะคา", 50},
{"Ko Kha", "Rice", "ข้าวราดคะน้าหมูกรอบเกาะคา", 60},

// --- Mae Tha --- (Lampang)
{"Mae Tha", "Noodle", "ก๋วยเตี๋ยวต้มยำดอยพระฌาน", 55},
{"Mae Tha", "Noodle", "ข้าวซอยไก่แม่ทะ", 50},
{"Mae Tha", "Noodle", "บะหมี่เกี๊ยวแม่ทะรสเด็ด", 50},
{"Mae Tha", "Noodle", "ขนมจีนน้ำเงี้ยวป้าคำแม่ทะ", 40},
{"Mae Tha", "Noodle", "เส้นเล็กน้ำใสแม่ทะ", 45},
{"Mae Tha", "Rice", "ข้าวมันไก่แม่ทะเจ้าเก่า", 50},
{"Mae Tha", "Rice", "ข้าวขาหมูแม่ทะรสเด็ด", 60},
{"Mae Tha", "Rice", "ลาบไก่แม่ทะเสิร์ฟพร้อมข้าว", 80},
{"Mae Tha", "Rice", "ครัวไม้แกะสลัก (ตามสั่ง)", 70},
{"Mae Tha", "Rice", "ข้าวแกงแม่ทะพุงกาง", 40},

// --- Chae Hom ---
{"Chae Hom", "Noodle", "ก๋วยเตี๋ยวเรือแจ้ห่ม", 45},
{"Chae Hom", "Noodle", "ข้าวซอยเนื้อแจ้ห่ม", 65},
{"Chae Hom", "Noodle", "บะหมี่น้ำหมูแดงแจ้ห่ม", 50},
{"Chae Hom", "Noodle", "เส้นหมี่ราดหน้าแจ้ห่ม", 55},
{"Chae Hom", "Noodle", "ก๋วยเตี๋ยวเป็ดแจ้ห่ม", 70},
{"Chae Hom", "Rice", "ข้าวมันไก่แจ้ห่มรสเด็ด", 50},
{"Chae Hom", "Rice", "ข้าวขาหมูสูตรโบราณแจ้ห่ม", 55},
{"Chae Hom", "Rice", "ข้าวราดลาบหมูคั่วแจ้ห่ม", 75},
{"Chae Hom", "Rice", "ครัวแจ้ห่มอาหารตามสั่ง", 55},
{"Chae Hom", "Rice", "ข้าวหน้าหมูกรอบแจ้ห่ม", 65},

// --- Mueang Pan ---
{"Mueang Pan", "Noodle", "ก๋วยเตี๋ยวริมน้ำตกแจ้ซ้อน", 55},
{"Mueang Pan", "Noodle", "ข้าวซอยไก่เมืองปาน", 50},
{"Mueang Pan", "Noodle", "บะหมี่น้ำใสเมืองปาน", 45},
{"Mueang Pan", "Noodle", "ขนมจีนน้ำยากะทิป้าหวาน", 40},
{"Mueang Pan", "Noodle", "เย็นตาโฟเครื่องทรงเมืองปาน", 50},
{"Mueang Pan", "Rice", "ข้าวไข่เจียวแจ้ซ้อน (ไข่น้ำแร่)", 40},
{"Mueang Pan", "Rice", "ข้าวมันไก่เมืองปาน", 50},
{"Mueang Pan", "Rice", "ข้าวขาหมูเมืองปานรสเด็ด", 60},
{"Mueang Pan", "Rice", "ครัวเมืองปานตามสั่ง", 55},
{"Mueang Pan", "Rice", "ลาบปลาเมืองปานพร้อมข้าว", 90},

// --- Ngao ---
{"Ngao", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นงาว", 50},
{"Ngao", "Noodle", "ข้าวซอยน่องไก่งาวรสเด็ด", 55},
{"Ngao", "Noodle", "บะหมี่เกี๊ยวงาวโบราณ", 50},
{"Ngao", "Noodle", "เส้นเล็กต้มยำน้ำข้นงาว", 50},
{"Ngao", "Noodle", "ขนมจีนน้ำเงี้ยวงาว", 40},
{"Ngao", "Rice", "ข้าวมันไก่งาวเจ้าเก่า", 45},
{"Ngao", "Rice", "ข้าวขาหมูงาวรสเด็ด", 55},
{"Ngao", "Rice", "ข้าวหน้าเป็ดย่างงาว", 75},
{"Ngao", "Rice", "ครัวงาวอาหารป่า", 120},
{"Ngao", "Rice", "ข้าวผัดน้ำพริกหนุ่มงาว", 70},

// --- Mae Mo ---
{"Mae Mo", "Noodle", "ก๋วยเตี๋ยวเรือแม่เมาะ", 45},
{"Mae Mo", "Noodle", "ข้าวซอยไก่แม่เมาะ", 50},
{"Mae Mo", "Noodle", "บะหมี่หมูทอดแม่เมาะ", 55},
{"Mae Mo", "Noodle", "ก๋วยเตี๋ยวเนื้อน้ำตกแม่เมาะ", 65},
{"Mae Mo", "Noodle", "เส้นเล็กต้มยำไข่หวานแม่เมาะ", 60},
{"Mae Mo", "Rice", "ข้าวมันไก่ตอนแม่เมาะ", 50},
{"Mae Mo", "Rice", "ข้าวขาหมูแม่เมาะรสเด็ด", 60},
{"Mae Mo", "Rice", "ครัวเหมืองแม่เมาะตามสั่ง", 60},
{"Mae Mo", "Rice", "ข้าวหน้าหมูกรอบแม่เมาะ", 65},
{"Mae Mo", "Rice", "ข้าวราดพริกแกงหมูป่าแม่เมาะ", 70},

// --- Hang Chat ---
{"Hang Chat", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นห้างฉัตร", 50},
{"Hang Chat", "Noodle", "ข้าวซอยเนื้อห้างฉัตร", 65},
{"Hang Chat", "Noodle", "บะหมี่เกี๊ยวห้างฉัตรเจ้าเก่า", 50},
{"Hang Chat", "Noodle", "ขนมจีนน้ำยาป้าจู", 40},
{"Hang Chat", "Noodle", "เส้นหมี่ผัดไทยห้างฉัตร", 60},
{"Hang Chat", "Rice", "ข้าวขาหมูห้างฉัตรเจ้าเด็ด", 60},
{"Hang Chat", "Rice", "ข้าวมันไก่ห้างฉัตร", 50},
{"Hang Chat", "Rice", "ครัวตลาดทุ่งเกวียน (ตามสั่ง)", 80},
{"Hang Chat", "Rice", "ข้าวราดลาบหมูคั่วห้างฉัตร", 75},
{"Hang Chat", "Rice", "ข้าวหน้าหมูแดงห้างฉัตร", 55},

// --- Mueang Phrae ---
{"Mueang Phrae", "Noodle", "ขนมเส้นเมืองแพร่ (สูตรดั้งเดิม)", 35},
{"Mueang Phrae", "Noodle", "ก๋วยเตี๋ยวต้มยำโบราณประตูชัย", 45},
{"Mueang Phrae", "Noodle", "ข้าวซอยไก่แม่บุญคง", 50},
{"Mueang Phrae", "Noodle", "บะหมี่เกี๊ยวทำเองเจ้าเก่า", 50},
{"Mueang Phrae", "Noodle", "เย็นตาโฟเครื่องทรงเมืองแพร่", 50},
{"Mueang Phrae", "Rice", "ข้าวหน้าหมูแดงประตูชัย", 50},
{"Mueang Phrae", "Rice", "ข้าวมันไก่เพชรรัตน์", 50},
{"Mueang Phrae", "Rice", "ข้าวขาหมูเจ๊จูเมืองแพร่", 60},
{"Mueang Phrae", "Rice", "ข้าวกั้นจิ้น (ข้าวเงี้ยวโบราณ)", 40},
{"Mueang Phrae", "Rice", "ครัวไม้เมือง (อาหารตามสั่ง)", 100},

// --- Den Chai ---
{"Den Chai", "Noodle", "ก๋วยเตี๋ยวเรือปากทางเด่นชัย", 45},
{"Den Chai", "Noodle", "บะหมี่เกี๊ยวหน้าสถานีรถไฟเด่นชัย", 50},
{"Den Chai", "Noodle", "ข้าวซอยเนื้อน่องลายเด่นชัย", 60},
{"Den Chai", "Noodle", "ขนมจีนน้ำย้อยเด่นชัย", 40},
{"Den Chai", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นยาจีนเด่นชัย", 55},
{"Den Chai", "Rice", "ข้าวมันไก่เด่นชัยรสเด็ด", 45},
{"Den Chai", "Rice", "ข้าวขาหมูเด่นชัยเจ้าเก่า", 55},
{"Den Chai", "Rice", "ข้าวหน้าหมูกรอบเด่นชัย", 60},
{"Den Chai", "Rice", "ลาบขมเด่นชัยเสิร์ฟพร้อมข้าว", 80},
{"Den Chai", "Rice", "ครัวเด่นชัยตามสั่ง", 50},

// --- Rong Kwang ---
{"Rong Kwang", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นร้องกวาง", 50},
{"Rong Kwang", "Noodle", "ข้าวซอยไก่ร้องกวาง", 50},
{"Rong Kwang", "Noodle", "บะหมี่เกี๊ยวน้ำใสร้องกวาง", 45},
{"Rong Kwang", "Noodle", "เส้นเล็กต้มยำไข่หวานร้องกวาง", 55},
{"Rong Kwang", "Noodle", "ขนมจีนน้ำยากะทิร้องกวาง", 40},
{"Rong Kwang", "Rice", "ข้าวมันไก่ร้องกวางเจ้าเก่า", 50},
{"Rong Kwang", "Rice", "ข้าวขาหมูร้องกวางรสเด็ด", 60},
{"Rong Kwang", "Rice", "ข้าวหน้าเป็ดร้องกวาง", 75},
{"Rong Kwang", "Rice", "ลาบปลาคังร้องกวางพร้อมข้าว", 90},
{"Rong Kwang", "Rice", "ครัวร้องกวางอาหารตามสั่ง", 55},

// --- Long ---
{"Long", "Noodle", "ขนมเส้นน้ำย้อยเมืองลอง (ต้นตำรับ)", 40},
{"Long", "Noodle", "ก๋วยเตี๋ยวต้มยำถั่วลิสงคั่วเอง", 45},
{"Long", "Noodle", "บะหมี่แห้งหมูแดงเมืองลอง", 50},
{"Long", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกเมืองลอง", 45},
{"Long", "Noodle", "ข้าวซอยเนื้อเมืองลอง", 60},
{"Long", "Rice", "ข้าวมันไก่เมืองลองรสเด็ด", 50},
{"Long", "Rice", "ข้าวขาหมูเมืองลองสูตรโบราณ", 55},
{"Long", "Rice", "ข้าวราดลาบหมูคั่วเมืองลอง", 70},
{"Long", "Rice", "ครัวเมืองลองตามสั่ง", 50},
{"Long", "Rice", "ข้าวเหนียวส้มตำเมืองลอง", 80},

// --- Wang Chin ---
{"Wang Chin", "Noodle", "ก๋วยเตี๋ยวหมูหมักวังชิ้น", 45},
{"Wang Chin", "Noodle", "ข้าวซอยไก่วังชิ้น", 50},
{"Wang Chin", "Noodle", "ขนมจีนน้ำย้อยแม่จัน (สาขาวังชิ้น)", 40},
{"Wang Chin", "Noodle", "บะหมี่น้ำใสวังชิ้น", 45},
{"Wang Chin", "Noodle", "เส้นหมี่ราดหน้าเนื้อนุ่มวังชิ้น", 55},
{"Wang Chin", "Rice", "ข้าวมันไก่วังชิ้นเจ้าเก่า", 50},
{"Wang Chin", "Rice", "ข้าวขาหมูวังชิ้นรสเด็ด", 55},
{"Wang Chin", "Rice", "ลาบหมูวังชิ้นพร้อมข้าว", 80},
{"Wang Chin", "Rice", "ครัววังชิ้นอาหารป่า", 120},
{"Wang Chin", "Rice", "ข้าวแกงวังชิ้นพุงกาง", 40},

// --- Song ---
{"Song", "Noodle", "ก๋วยเตี๋ยวเรือเมืองสอง", 45},
{"Song", "Noodle", "ข้าวซอยเนื้อเมืองสอง", 60},
{"Song", "Noodle", "ขนมจีนน้ำเงี้ยวเมืองสอง", 40},
{"Song", "Noodle", "บะหมี่เกี๊ยวเมืองสองรสเด็ด", 50},
{"Song", "Noodle", "เส้นเล็กต้มยำสุโขทัย (สาขาสอง)", 50},
{"Song", "Rice", "ข้าวมันไก่ตอนเมืองสอง", 50},
{"Song", "Rice", "ข้าวขาหมูเมืองสองเจ้าเก่า", 60},
{"Song", "Rice", "ครัวริมทางเมืองสองตามสั่ง", 55},
{"Song", "Rice", "ข้าวราดพริกแกงปลาคังเมืองสอง", 85},
{"Song", "Rice", "ลาบเป็ดเมืองสองพร้อมข้าว", 100},


// --- Mueang Nan ---
{"Mueang Nan", "Noodle", "ข้าวซอยต้นน้ำ", 55},
{"Mueang Nan", "Noodle", "ก๋วยเตี๋ยวไร้เส้นน่าน", 60},
{"Mueang Nan", "Noodle", "ขนมจีนน้ำเงี้ยวป้าวันดี", 40},
{"Mueang Nan", "Noodle", "บะหมี่เกี๊ยวเจ้าเก่ากาดน่าน", 50},
{"Mueang Nan", "Noodle", "ก๋วยเตี๋ยวเป็ดตุ๋นน้ำแดง", 65},
{"Mueang Nan", "Rice", "ข้าวหมูแดงเลิศรส", 50},
{"Mueang Nan", "Rice", "ข้าวมันไก่แม่นาง", 50},
{"Mueang Nan", "Rice", "ฮือนฮอม (อาหารพื้นเมือง/ข้าว)", 150},
{"Mueang Nan", "Rice", "ข้าวแกงเผ็ดน่านโบราณ", 45},
{"Mueang Nan", "Rice", "ข้าวหน้าเป็ดย่างน่าน", 75},

// --- Phu Phiang ---
{"Phu Phiang", "Noodle", "ก๋วยเตี๋ยวเรือภูเพียง", 45},
{"Phu Phiang", "Noodle", "ข้าวซอยไก่ภูเพียง", 50},
{"Phu Phiang", "Noodle", "บะหมี่น้ำหมูแดงภูเพียง", 45},
{"Phu Phiang", "Noodle", "เส้นเล็กต้มยำภูเพียงรสเด็ด", 50},
{"Phu Phiang", "Noodle", "ขนมจีนน้ำยากะทิภูเพียง", 40},
{"Phu Phiang", "Rice", "ข้าวมันไก่ภูเพียงเจ้าเก่า", 50},
{"Phu Phiang", "Rice", "ข้าวขาหมูภูเพียงรสเด็ด", 60},
{"Phu Phiang", "Rice", "ครัวภูเพียงอาหารตามสั่ง", 55},
{"Phu Phiang", "Rice", "ข้าวราดลาบหมูคั่วน่าน", 70},
{"Phu Phiang", "Rice", "ข้าวหน้าหมูกรอบภูเพียง", 65},

// --- Pua ---
{"Pua", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่ลวกปัว", 50},
{"Pua", "Noodle", "ข้าวซอยน่องไก่ปัวรสเด็ด", 55},
{"Pua", "Noodle", "ขนมจีนน้ำย้อยเมืองปัว", 40},
{"Pua", "Noodle", "บะหมี่เกี๊ยวทำเองปัว", 50},
{"Pua", "Noodle", "เส้นหมี่ราดหน้าเนื้อนุ่มปัว", 55},
{"Pua", "Rice", "ข้าวมันไก่ปัวเจ้าเก่า", 50},
{"Pua", "Rice", "ข้าวขาหมูปัวสูตรโบราณ", 60},
{"Pua", "Rice", "ฟาร์มเห็ดบ้านหัวน้ำ (เมนูข้าวเห็ด)", 120},
{"Pua", "Rice", "ลาบไก่ปัวพร้อมข้าวเหนียว", 80},
{"Pua", "Rice", "ข้าวผัดน้ำพริกหนุ่มปัว", 70},

// --- Tha Wang Pha ---
{"Tha Wang Pha", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นท่าวังผา", 50},
{"Tha Wang Pha", "Noodle", "ข้าวซอยเนื้อท่าวังผา", 65},
{"Tha Wang Pha", "Noodle", "บะหมี่เกี๊ยวน้านใสท่าวังผา", 45},
{"Tha Wang Pha", "Noodle", "เส้นเล็กต้มยำน้ำข้นท่าวังผา", 50},
{"Tha Wang Pha", "Noodle", "ก๋วยเตี๋ยวเรือท่าวังผารสเด็ด", 45},
{"Tha Wang Pha", "Rice", "ข้าวมันไก่ท่าวังผาเจ้าเก่า", 50},
{"Tha Wang Pha", "Rice", "ข้าวขาหมูท่าวังผารสเด็ด", 60},
{"Tha Wang Pha", "Rice", "ลาบปลาท่าวังผาเสิร์ฟพร้อมข้าว", 90},
{"Tha Wang Pha", "Rice", "ครัวริมทางท่าวังผาตามสั่ง", 55},
{"Tha Wang Pha", "Rice", "ข้าวหน้าหมูทอดท่าวังผา", 50},

// --- Na Noi ---
{"Na Noi", "Noodle", "ก๋วยเตี๋ยวเรือนาน้อย", 45},
{"Na Noi", "Noodle", "ข้าวซอยไก่นาน้อยรสเด็ด", 50},
{"Na Noi", "Noodle", "บะหมี่หมูทอดนาน้อย", 55},
{"Na Noi", "Noodle", "ขนมจีนน้ำเงี้ยวนาน้อย", 40},
{"Na Noi", "Noodle", "เส้นเล็กน้ำใสนาน้อย", 45},
{"Na Noi", "Rice", "ข้าวมันไก่นาน้อยรสเด็ด", 45},
{"Na Noi", "Rice", "ข้าวขาหมูนาน้อยเจ้าเก่า", 55},
{"Na Noi", "Rice", "ครัวเสม็ดชุน (อาหารตามสั่ง)", 70},
{"Na Noi", "Rice", "ลาบหมูคั่วนาน้อยพร้อมข้าว", 80},
{"Na Noi", "Rice", "ข้าวราดพริกแกงหมูป่านาน้อย", 75},

// --- Bo Kluea ---
{"Bo Kluea", "Noodle", "ก๋วยเตี๋ยวต้มยำเกลือสินเธาว์", 55},
{"Bo Kluea", "Noodle", "ข้าวซอยไก่บ่อเกลือ", 60},
{"Bo Kluea", "Noodle", "บะหมี่น้ำใสบ่อเกลือ", 50},
{"Bo Kluea", "Noodle", "ขนมจีนน้ำเงี้ยวบ่อเกลือโบราณ", 45},
{"Bo Kluea", "Noodle", "เส้นหมี่ราดหน้าหมูหมัก", 60},
{"Bo Kluea", "Rice", "ไก่ทอดเกลือสินเธาว์พร้อมข้าว", 100},
{"Bo Kluea", "Rice", "ข้าวมันไก่บ่อเกลือรสเด็ด", 55},
{"Bo Kluea", "Rice", "ข้าวขาหมูบ่อเกลือเจ้าเก่า", 65},
{"Bo Kluea", "Rice", "ครัวไอหมอก (อาหารตามสั่ง)", 90},
{"Bo Kluea", "Rice", "ข้าวราดหมูกระเทียมพริกไทย", 60},

// --- Chiang Klang ---
{"Chiang Klang", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นเชียงกลาง", 50},
{"Chiang Klang", "Noodle", "ข้าวซอยเนื้อเชียงกลาง", 65},
{"Chiang Klang", "Noodle", "บะหมี่เกี๊ยวเชียงกลางรสเด็ด", 50},
{"Chiang Klang", "Noodle", "ขนมจีนน้ำยาป้าคำเชียงกลาง", 40},
{"Chiang Klang", "Noodle", "เส้นเล็กต้มยำเชียงกลาง", 50},
{"Chiang Klang", "Rice", "ข้าวมันไก่เชียงกลางเจ้าเก่า", 50},
{"Chiang Klang", "Rice", "ข้าวขาหมูเชียงกลางรสเด็ด", 60},
{"Chiang Klang", "Rice", "ครัวเชียงกลางอาหารตามสั่ง", 55},
{"Chiang Klang", "Rice", "ข้าวหน้าเป็ดเชียงกลาง", 75},
{"Chiang Klang", "Rice", "ลาบไก่เชียงกลางพร้อมข้าวเหนียว", 80},

// --- Mueang Uttaradit ---
{"Mueang Uttaradit", "Noodle", "ก๋วยเตี๋ยวเรือเป่าปาก", 50},
{"Mueang Uttaradit", "Noodle", "บะหมี่เกี๊ยวทำเองเจ้าเก่า", 50},
{"Mueang Uttaradit", "Noodle", "เส้นเล็กต้มยำน้ำข้นเมืองอุตรดิตถ์", 55},
{"Mueang Uttaradit", "Noodle", "ราดหน้ายอดผักรถไฟ", 60},
{"Mueang Uttaradit", "Noodle", "เย็นตาโฟเจ๊หมวย", 50},
{"Mueang Uttaradit", "Rice", "ข้าวมันไก่ปักษ์ใต้ (สาขาอุตรดิตถ์)", 50},
{"Mueang Uttaradit", "Rice", "ข้าวหมูแดงหมูกรอบรสเด็ด", 55},
{"Mueang Uttaradit", "Rice", "ข้าวขาหมูบางรัก (อุตรดิตถ์)", 60},
{"Mueang Uttaradit", "Rice", "ครัวริมน้ำตามสั่ง", 90},
{"Mueang Uttaradit", "Rice", "ข้าวหน้าเป็ดย่างเมืองท่า", 75},

// --- Nam Pat ---
{"Nam Pat", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นน้ำปาด", 50},
{"Nam Pat", "Noodle", "ข้าวซอยไก่น้ำปาดรสเด็ด", 55},
{"Nam Pat", "Noodle", "บะหมี่หมูแดงน้ำปาด", 45},
{"Nam Pat", "Noodle", "ก๋วยเตี๋ยวเนื้อน้ำตกน้ำปาด", 60},
{"Nam Pat", "Noodle", "ขนมจีนน้ำยากะทิป้าจันทร์", 40},
{"Nam Pat", "Rice", "ข้าวมันไก่น้ำปาดเจ้าเก่า", 50},
{"Nam Pat", "Rice", "ข้าวขาหมูน้ำปาดรสเด็ด", 60},
{"Nam Pat", "Rice", "ลาบหมูน้ำปาดเสิร์ฟพร้อมข้าว", 80},
{"Nam Pat", "Rice", "ครัวขุนเขาอาหารตามสั่ง", 70},
{"Nam Pat", "Rice", "ข้าวราดพริกแกงปลาคัง", 85},

// --- Lablae ---
{"Lablae", "Noodle", "ข้าวพันผักลับแล (ของดีลับแล)", 40},
{"Lablae", "Noodle", "หมี่พันลับแลเจ้าต้นตำรับ", 35},
{"Lablae", "Noodle", "ก๋วยเตี๋ยวไทยโบราณลับแล", 45},
{"Lablae", "Noodle", "บะหมี่น้ำใสตลาดลับแล", 45},
{"Lablae", "Noodle", "เส้นเล็กต้มยำแห้งลับแล", 50},
{"Lablae", "Rice", "ข้าวแคบพันผักลับแล", 45},
{"Lablae", "Rice", "ข้าวมันไก่ลับแลรสเด็ด", 50},
{"Lablae", "Rice", "ข้าวขาหมูสูตรลับแลโบราณ", 60},
{"Lablae", "Rice", "ลาบไก่ลับแลพร้อมข้าวเหนียว", 80},
{"Lablae", "Rice", "ข้าวหน้าหมูทอดลับแล", 55},

// --- Tha Pla ---
{"Tha Pla", "Noodle", "ก๋วยเตี๋ยวปลาเขื่อนสิริกิติ์", 65},
{"Tha Pla", "Noodle", "บะหมี่น้ำท่าปลารสเด็ด", 50},
{"Tha Pla", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกท่าปลา", 45},
{"Tha Pla", "Noodle", "เส้นเล็กต้มยำปลาคัง", 70},
{"Tha Pla", "Noodle", "ขนมจีนน้ำเงี้ยวท่าปลา", 40},
{"Tha Pla", "Rice", "ข้าวมันไก่ตอนท่าปลา", 50},
{"Tha Pla", "Rice", "ข้าวขาหมูท่าปลาเจ้าเก่า", 55},
{"Tha Pla", "Rice", "ลาบปลาท่าปลาเสิร์ฟพร้อมข้าว", 100},
{"Tha Pla", "Rice", "ครัวริมเขื่อน (ตามสั่ง)", 120},
{"Tha Pla", "Rice", "ข้าวผัดต้มยำทะเลท่าปลา", 85},

// --- Phichai ---
{"Phichai", "Noodle", "ก๋วยเตี๋ยวพระยาพิชัย", 50},
{"Phichai", "Noodle", "บะหมี่หมูแดงพิชัยรสเด็ด", 45},
{"Phichai", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่ต้มพิชัย", 55},
{"Phichai", "Noodle", "เย็นตาโฟพิชัยเจ้าเก่า", 50},
{"Phichai", "Noodle", "ผัดไทยพิชัยโบราณ", 60},
{"Phichai", "Rice", "ข้าวมันไก่พิชัยเจ้าเด็ด", 50},
{"Phichai", "Rice", "ข้าวขาหมูพิชัยรสเลิศ", 60},
{"Phichai", "Rice", "ข้าวแกงแม่ประนอมพิชัย", 40},
{"Phichai", "Rice", "ลาบไก่พิชัยพร้อมข้าว", 80},
{"Phichai", "Rice", "ครัวพิชัยอาหารตามสั่ง", 55},

// --- Mueang Tak ---
{"Mueang Tak", "Noodle", "ก๋วยเตี๋ยวพื้นเมืองตาก (ใส่มะนาวสด)", 45},
{"Mueang Tak", "Noodle", "บะหมี่น้ำใสโบราณเมืองตาก", 45},
{"Mueang Tak", "Noodle", "ผัดไทยเมืองตากเจ้าเด็ด", 50},
{"Mueang Tak", "Noodle", "เส้นเล็กต้มยำน้ำข้นริมโขง", 50},
{"Mueang Tak", "Noodle", "ขนมจีนน้ำยาปลาเจ้าเก่า", 40},
{"Mueang Tak", "Rice", "ข้าวมันไก่ตอนเมืองตาก", 50},
{"Mueang Tak", "Rice", "ข้าวขาหมูตากรสเด็ด", 55},
{"Mueang Tak", "Rice", "ลาบหมูตากพร้อมข้าวเหนียว", 80},
{"Mueang Tak", "Rice", "ครัวตากสินตามสั่ง", 60},
{"Mueang Tak", "Rice", "ข้าวแกงเมืองตากพุงกาง", 40},

// --- Umphang ---
{"Umphang", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นอุ้มผาง", 50},
{"Umphang", "Noodle", "บะหมี่น้ำใสอุ้มผางดอยสูง", 50},
{"Umphang", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกอุ้มผาง", 45},
{"Umphang", "Noodle", "เส้นเล็กต้มยำปลาคังอุ้มผาง", 70},
{"Umphang", "Noodle", "ขนมจีนน้ำยากะทิป้าหวัง", 40},
{"Umphang", "Rice", "ข้าวมันไก่อุ้มผางรสเด็ด", 50},
{"Umphang", "Rice", "ข้าวขาหมูอุ้มผางเจ้าเก่า", 60},
{"Umphang", "Rice", "ลาบปลาคังเสิร์ฟพร้อมข้าว", 100},
{"Umphang", "Rice", "ครัวทีลอซูตามสั่ง", 80},
{"Umphang", "Rice", "ข้าวหน้าหมูกรอบอุ้มผาง", 65},

// --- Tha Song Yang ---
{"Tha Song Yang", "Noodle", "ก๋วยเตี๋ยวหมูหมักท่าสองยาง", 45},
{"Tha Song Yang", "Noodle", "บะหมี่น้ำใสท่าสองยาง", 45},
{"Tha Song Yang", "Noodle", "ก๋วยเตี๋ยวเรือริมเมย", 45},
{"Tha Song Yang", "Noodle", "เส้นเล็กต้มยำแห้งท่าสองยาง", 50},
{"Tha Song Yang", "Noodle", "เย็นตาโฟท่าสองยางโบราณ", 50},
{"Tha Song Yang", "Rice", "ข้าวมันไก่ท่าสองยางรสเด็ด", 50},
{"Tha Song Yang", "Rice", "ข้าวขาหมูท่าสองยางเจ้าเก่า", 55},
{"Tha Song Yang", "Rice", "ครัวชายแดนตามสั่ง", 60},
{"Tha Song Yang", "Rice", "ลาบไก่ท่าสองยางพร้อมข้าว", 80},
{"Tha Song Yang", "Rice", "ข้าวหน้าหมูทอดท่าสองยาง", 50},

// --- Phop Phra ---
{"Phop Phra", "Noodle", "ก๋วยเตี๋ยวต้มยำพบพระรสแซ่บ", 50},
{"Phop Phra", "Noodle", "บะหมี่เกี๊ยวพบพระเจ้าเก่า", 50},
{"Phop Phra", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกพบพระ", 45},
{"Phop Phra", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Phop Phra", "Noodle", "ราดหน้ายอดผักพบพระ", 55},
{"Phop Phra", "Rice", "ข้าวขาหมูพบพระรสเด็ด", 60},
{"Phop Phra", "Rice", "ข้าวมันไก่พบพระเลิศรส", 50},
{"Phop Phra", "Rice", "ครัวดาวลอย (ตามสั่ง)", 70},
{"Phop Phra", "Rice", "ลาบหมูพบพระพร้อมข้าว", 80},
{"Phop Phra", "Rice", "ข้าวหน้าหมูกรอบพบพระ", 60},

// --- Mae Ramat ---
{"Mae Ramat", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นแม่ระมาด", 50},
{"Mae Ramat", "Noodle", "บะหมี่น้ำใสแม่ระมาดรสเด็ด", 45},
{"Mae Ramat", "Noodle", "เส้นเล็กต้มยำน้ำข้นแม่ระมาด", 50},
{"Mae Ramat", "Noodle", "ก๋วยเตี๋ยวเรือปากทางแม่ระมาด", 45},
{"Mae Ramat", "Noodle", "ขนมจีนน้ำยากะทิป้าจันทร์", 40},
{"Mae Ramat", "Rice", "ข้าวมันไก่แม่ระมาดเจ้าเก่า", 50},
{"Mae Ramat", "Rice", "ข้าวขาหมูแม่ระมาดรสแซ่บ", 60},
{"Mae Ramat", "Rice", "ครัวแม่ระมาดตามสั่ง", 55},
{"Mae Ramat", "Rice", "ลาบปลาแม่ระมาดพร้อมข้าว", 90},
{"Mae Ramat", "Rice", "ข้าวหน้าเป็ดแม่ระมาด", 75},

// --- Mae Sot ---
{"Mae Sot", "Noodle", "ก๋วยเตี๋ยวเนื้อแม่สอดรสเด็ด", 70},
{"Mae Sot", "Noodle", "บะหมี่ไทใหญ่แม่สอด", 50},
{"Mae Sot", "Noodle", "ข้าวซอยเนื้อแม่สอดโบราณ", 65},
{"Mae Sot", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกแม่สอด", 50},
{"Mae Sot", "Noodle", "เส้นหมี่ราดหน้าเนื้อนุ่ม", 60},
{"Mae Sot", "Rice", "ข้าวขาหมูแม่สอด (เจ้าดัง)", 60},
{"Mae Sot", "Rice", "ข้าวหมกไก่ฮาลาลแม่สอด", 60},
{"Mae Sot", "Rice", "ข้าวมันไก่แม่สอดรสเด็ด", 50},
{"Mae Sot", "Rice", "ครัวแม่สอดอาหารพม่า (ข้าว)", 90},
{"Mae Sot", "Rice", "ข้าวหน้าเป็ดแม่สอด", 75},

// --- Ban Tak ---
{"Ban Tak", "Noodle", "ก๋วยเตี๋ยวหมูโบราณบ้านตาก", 45},
{"Ban Tak", "Noodle", "บะหมี่น้ำใสบ้านตากรสเด็ด", 45},
{"Ban Tak", "Noodle", "เส้นเล็กต้มยำไข่เค็มบ้านตาก", 55},
{"Ban Tak", "Noodle", "เย็นตาโฟบ้านตากหน้าวัด", 50},
{"Ban Tak", "Noodle", "ก๋วยเตี๋ยวเรือบ้านตากเจ้าเก่า", 45},
{"Ban Tak", "Rice", "ข้าวมันไก่บ้านตากรสเลิศ", 50},
{"Ban Tak", "Rice", "ข้าวขาหมูบ้านตากรสเด็ด", 60},
{"Ban Tak", "Rice", "ครัวริมน้ำบ้านตากตามสั่ง", 65},
{"Ban Tak", "Rice", "ลาบหมูบ้านตากพร้อมข้าว", 80},
{"Ban Tak", "Rice", "ข้าวหน้าหมูกรอบบ้านตาก", 60},

// --- Sam Ngao ---
{"Sam Ngao", "Noodle", "ก๋วยเตี๋ยวเรือเขื่อนภูมิพล", 50},
{"Sam Ngao", "Noodle", "บะหมี่น้ำหมูแดงสามเงา", 45},
{"Sam Ngao", "Noodle", "ก๋วยเตี๋ยวปลาเขื่อนสามเงา", 70},
{"Sam Ngao", "Noodle", "เย็นตาโฟสามเงาน้ำข้น", 55},
{"Sam Ngao", "Noodle", "ผัดไทยโบราณสามเงา", 50},
{"Sam Ngao", "Rice", "ข้าวมันไก่สามเงารสเด็ด", 50},
{"Sam Ngao", "Rice", "ข้าวขาหมูสามเงาสูตรโบราณ", 55},
{"Sam Ngao", "Rice", "ครัวริมเขื่อนภูมิพลตามสั่ง", 120},
{"Sam Ngao", "Rice", "ข้าวผัดปลาคังเขื่อน", 90},
{"Sam Ngao", "Rice", "ข้าวราดพริกแกงหมูป่าสามเงา", 75},

// --- Mueang Sukhothai ---
{"Mueang Sukhothai", "Noodle", "ก๋วยเตี๋ยวสุโขทัยเจ๊แฮ", 50},
{"Mueang Sukhothai", "Noodle", "ก๋วยเตี๋ยวสุโขทัยแม่บุญมี", 50},
{"Mueang Sukhothai", "Noodle", "บะหมี่แห้งสุโขทัยตาพุ้ย", 50},
{"Mueang Sukhothai", "Noodle", "ก๋วยเตี๋ยวเป็ดต้มยำสุโขทัย", 60},
{"Mueang Sukhothai", "Noodle", "ผัดไทยสุโขทัยโบราณ", 55},
{"Mueang Sukhothai", "Rice", "ข้าวขาหมูสุโขทัยรสเด็ด", 55},
{"Mueang Sukhothai", "Rice", "ข้าวมันไก่สุโขทัยเจ้าเก่า", 50},
{"Mueang Sukhothai", "Rice", "ข้าวหมูแดงสุโขทัยเจ้าดัง", 50},
{"Mueang Sukhothai", "Rice", "ครัวสุโขทัยอาหารตามสั่ง", 70},
{"Mueang Sukhothai", "Rice", "ข้าวหน้าหมูกรอบสุโขทัย", 60},

// --- Khiri Mat ---
{"Khiri Mat", "Noodle", "ก๋วยเตี๋ยวต้มยำคีรีมาศ", 45},
{"Khiri Mat", "Noodle", "บะหมี่หมูแดงคีรีมาศรสเด็ด", 45},
{"Khiri Mat", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกคีรีมาศ", 40},
{"Khiri Mat", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Khiri Mat", "Noodle", "ผัดไทยโบราณคีรีมาศ", 50},
{"Khiri Mat", "Rice", "ข้าวมันไก่คีรีมาศเจ้าเก่า", 45},
{"Khiri Mat", "Rice", "ข้าวขาหมูคีรีมาศรสเด็ด", 55},
{"Khiri Mat", "Rice", "ครัวคีรีมาศตามสั่ง", 50},
{"Khiri Mat", "Rice", "ลาบหมูคีรีมาศพร้อมข้าว", 80},
{"Khiri Mat", "Rice", "ข้าวแกงคีรีมาศพุงกาง", 40},

// --- Si Satchanalai ---
{"Si Satchanalai", "Noodle", "ข้าวเปิ๊บบ้านนาต้นจั่น", 40},
{"Si Satchanalai", "Noodle", "หมี่พันศรีสัชนาลัย", 35},
{"Si Satchanalai", "Noodle", "ก๋วยเตี๋ยวแบศรีสัชนาลัย", 45},
{"Si Satchanalai", "Noodle", "บะหมี่แห้งต้มยำศรีสัช", 50},
{"Si Satchanalai", "Noodle", "ก๋วยเตี๋ยวเรือเมืองเชลียง", 45},
{"Si Satchanalai", "Rice", "ข้าวมันไก่ศรีสัชนาลัยรสเด็ด", 50},
{"Si Satchanalai", "Rice", "ข้าวขาหมูสูตรโบราณศรีสัช", 60},
{"Si Satchanalai", "Rice", "ข้าวราดลาบหมูคั่วศรีสัช", 75},
{"Si Satchanalai", "Rice", "ครัวศรีสัชอาหารตามสั่ง", 60},
{"Si Satchanalai", "Rice", "ข้าวหน้าหมูกรอบศรีสัช", 65},

// --- Sawankhalok ---
{"Sawankhalok", "Noodle", "ก๋วยเตี๋ยวสุโขทัยสวรรคโลก", 50},
{"Sawankhalok", "Noodle", "บะหมี่เกี๊ยวทำเองสวรรคโลก", 50},
{"Sawankhalok", "Noodle", "เส้นเล็กต้มยำสุโขทัยน้ำข้น", 50},
{"Sawankhalok", "Noodle", "เย็นตาโฟสวรรคโลกรสเด็ด", 50},
{"Sawankhalok", "Noodle", "ราดหน้ายอดผักสวรรคโลก", 55},
{"Sawankhalok", "Rice", "ข้าวมันไก่สวรรคโลกเจ้าเก่า", 50},
{"Sawankhalok", "Rice", "ข้าวขาหมูสวรรคโลกรสเด็ด", 60},
{"Sawankhalok", "Rice", "ข้าวหมูแดงสวรรคโลกเจ้าเด็ด", 55},
{"Sawankhalok", "Rice", "ครัวริมทางสวรรคโลกตามสั่ง", 55},
{"Sawankhalok", "Rice", "ลาบไก่สวรรคโลกพร้อมข้าว", 80},

// --- Thung Saliam ---
{"Thung Saliam", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นทุ่งเสลี่ยม", 50},
{"Thung Saliam", "Noodle", "บะหมี่น้ำใสทุ่งเสลี่ยมดั้งเดิม", 45},
{"Thung Saliam", "Noodle", "เส้นเล็กต้มยำแห้งสุโขทัย", 50},
{"Thung Saliam", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกทุ่งเสลี่ยม", 45},
{"Thung Saliam", "Noodle", "เย็นตาโฟทุ่งเสลี่ยมรสแซ่บ", 55},
{"Thung Saliam", "Rice", "ข้าวมันไก่ทุ่งเสลี่ยมรสเด็ด", 50},
{"Thung Saliam", "Rice", "ข้าวขาหมูทุ่งเสลี่ยมเจ้าเก่า", 55},
{"Thung Saliam", "Rice", "ลาบปลาทุ่งเสลี่ยมเสิร์ฟพร้อมข้าว", 90},
{"Thung Saliam", "Rice", "ครัวทุ่งเสลี่ยมอาหารตามสั่ง", 55},
{"Thung Saliam", "Rice", "ข้าวแกงแม่ประนอมทุ่งเสลี่ยม", 40},

// --- Ban Dan Lan Hoi ---
{"Ban Dan Lan Hoi", "Noodle", "ก๋วยเตี๋ยวเรือบ้านด่าน", 45},
{"Ban Dan Lan Hoi", "Noodle", "บะหมี่หมูแดงลานหอย", 45},
{"Ban Dan Lan Hoi", "Noodle", "เส้นเล็กต้มยำสุโขทัยลานหอย", 50},
{"Ban Dan Lan Hoi", "Noodle", "ขนมจีนน้ำยากะทิป้าจันทร์", 40},
{"Ban Dan Lan Hoi", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่หวานลานหอย", 55},
{"Ban Dan Lan Hoi", "Rice", "ข้าวมันไก่บ้านด่านรสเด็ด", 45},
{"Ban Dan Lan Hoi", "Rice", "ข้าวขาหมูบ้านด่านเจ้าเก่า", 55},
{"Ban Dan Lan Hoi", "Rice", "ครัวลานหอยตามสั่ง", 50},
{"Ban Dan Lan Hoi", "Rice", "ข้าวหน้าหมูกรอบบ้านด่าน", 65},
{"Ban Dan Lan Hoi", "Rice", "ลาบหมูบ้านด่านพร้อมข้าว", 75},

// --- Si Samrong ---
{"Si Samrong", "Noodle", "ก๋วยเตี๋ยวต้มยำศรีสำโรงรสเด็ด", 50},
{"Si Samrong", "Noodle", "บะหมี่น้ำใสศรีสำโรงเจ้าเก่า", 45},
{"Si Samrong", "Noodle", "ก๋วยเตี๋ยวเป็ดตุ๋นศรีสำโรง", 65},
{"Si Samrong", "Noodle", "ผัดไทยสุโขทัยศรีสำโรง", 55},
{"Si Samrong", "Noodle", "เส้นหมี่ราดหน้าศรีสำโรง", 50},
{"Si Samrong", "Rice", "ข้าวมันไก่ศรีสำโรงรสเลิศ", 50},
{"Si Samrong", "Rice", "ข้าวขาหมูศรีสำโรงรสเด็ด", 60},
{"Si Samrong", "Rice", "ข้าวหมูแดงศรีสำโรงเจ้าดัง", 55},
{"Si Samrong", "Rice", "ครัวศรีสำโรงตามสั่ง", 60},
{"Si Samrong", "Rice", "ลาบปลาศรีสำโรงพร้อมข้าว", 90},

// --- Mueang Phitsanulok ---
{"Mueang Phitsanulok", "Noodle", "ก๋วยเตี๋ยวห้อยขาริมน่าน", 50},
{"Mueang Phitsanulok", "Noodle", "ก๋วยเตี๋ยวไก่ไทยป้าล้อม", 60},
{"Mueang Phitsanulok", "Noodle", "จุกไก่ไทย (บะหมี่โบราณ)", 55},
{"Mueang Phitsanulok", "Noodle", "เย็นตาโฟเจ๊ธง", 50},
{"Mueang Phitsanulok", "Noodle", "ราดหน้ายอดผักสองแคว", 55},
{"Mueang Phitsanulok", "Rice", "ข้าวมันไก่พลายชุมพล", 50},
{"Mueang Phitsanulok", "Rice", "ข้าวหมูแดงสูตรนครปฐม (สาขาพิษณุโลก)", 55},
{"Mueang Phitsanulok", "Rice", "ข้าวขาหมูประตูเมือง", 60},
{"Mueang Phitsanulok", "Rice", "ข้าวผัดคลุกน้ำพริกลงเรือ", 80},
{"Mueang Phitsanulok", "Rice", "ครัวผักบุ้งลอยฟ้า (อาหารตามสั่ง)", 120},

// --- Nakhon Thai ---
{"Nakhon Thai", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นนครไทย", 50},
{"Nakhon Thai", "Noodle", "บะหมี่น้ำใสนครไทยรสเด็ด", 45},
{"Nakhon Thai", "Noodle", "เส้นเล็กต้มยำดอยร่องกล้า", 55},
{"Nakhon Thai", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกนครไทย", 45},
{"Nakhon Thai", "Noodle", "ขนมจีนน้ำยากะทิป้าจันทร์", 40},
{"Nakhon Thai", "Rice", "ข้าวมันไก่นครไทยเจ้าเก่า", 50},
{"Nakhon Thai", "Rice", "ข้าวขาหมูพิชิตนครไทย", 60},
{"Nakhon Thai", "Rice", "ข้าวหน้าหมูกรอบนครไทย", 65},
{"Nakhon Thai", "Rice", "ครัวนครไทยอาหารตามสั่ง", 55},
{"Nakhon Thai", "Rice", "ลาบหมูนครไทยเสิร์ฟพร้อมข้าว", 80},

// --- Wang Thong ---
{"Wang Thong", "Noodle", "ก๋วยเตี๋ยวเรือวังทองรสเด็ด", 45},
{"Wang Thong", "Noodle", "ผัดไทยโบราณวังทอง", 50},
{"Wang Thong", "Noodle", "บะหมี่น้ำใสวังทองเจ้าเก่า", 45},
{"Wang Thong", "Noodle", "เย็นตาโฟวังทองหน้าตลาด", 50},
{"Wang Thong", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่เค็ม", 55},
{"Wang Thong", "Rice", "ข้าวมันไก่วังทองเลิศรส", 50},
{"Wang Thong", "Rice", "ข้าวขาหมูวังทองรสเด็ด", 55},
{"Wang Thong", "Rice", "ข้าวหน้าเป็ดวังทอง", 75},
{"Wang Thong", "Rice", "ครัวส้มตำวังทอง (ข้าวเหนียว)", 80},
{"Wang Thong", "Rice", "ข้าวแกงแม่ประนอมวังทอง", 40},

// --- Noen Maprang ---
{"Noen Maprang", "Noodle", "ก๋วยเตี๋ยวต้มยำเนินมะปราง", 50},
{"Noen Maprang", "Noodle", "บะหมี่เกี๊ยวทำเองเนินมะปราง", 50},
{"Noen Maprang", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นปลา", 45},
{"Noen Maprang", "Noodle", "ก๋วยเตี๋ยวเรือเนินมะปรางรสเด็ด", 45},
{"Noen Maprang", "Noodle", "ขนมจีนน้ำเงี้ยว (สูตรเหนือในเนินมะปราง)", 40},
{"Noen Maprang", "Rice", "ข้าวมันไก่เนินมะปรางเจ้าเก่า", 50},
{"Noen Maprang", "Rice", "ข้าวขาหมูเนินมะปรางรสแซ่บ", 60},
{"Noen Maprang", "Rice", "ลาบปลาเนินมะปรางพร้อมข้าว", 90},
{"Noen Maprang", "Rice", "ครัวชมวิวเนินมะปราง (ตามสั่ง)", 100},
{"Noen Maprang", "Rice", "ข้าวราดคะน้าหมูกรอบ", 60},

// --- Chat Trakan ---
{"Chat Trakan", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นชาติตระการ", 45},
{"Chat Trakan", "Noodle", "บะหมี่น้ำใสชาติตระการรสเด็ด", 45},
{"Chat Trakan", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกริมทาง", 45},
{"Chat Trakan", "Noodle", "ผัดไทยโบราณชาติตระการ", 50},
{"Chat Trakan", "Noodle", "ก๋วยเตี๋ยวเป็ดชาติตระการ", 65},
{"Chat Trakan", "Rice", "ข้าวมันไก่ชาติตระการเจ้าเก่า", 50},
{"Chat Trakan", "Rice", "ข้าวขาหมูชาติตระการรสเด็ด", 55},
{"Chat Trakan", "Rice", "ครัวชาติตระการตามสั่ง", 55},
{"Chat Trakan", "Rice", "ลาบไก่ชาติตระการพร้อมข้าว", 80},
{"Chat Trakan", "Rice", "ข้าวหน้าหมูกรอบชาติตระการ", 60},

// --- Wat Bot ---
{"Wat Bot", "Noodle", "ก๋วยเตี๋ยวปลาน้ำแควน้อย", 65},
{"Wat Bot", "Noodle", "ก๋วยเตี๋ยวต้มยำวัดโบสถ์", 50},
{"Wat Bot", "Noodle", "บะหมี่หมูแดงวัดโบสถ์รสเด็ด", 50},
{"Wat Bot", "Noodle", "เย็นตาโฟวัดโบสถ์โบราณ", 50},
{"Wat Bot", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 45},
{"Wat Bot", "Rice", "ข้าวมันไก่วัดโบสถ์เจ้าเก่า", 50},
{"Wat Bot", "Rice", "ข้าวขาหมูวัดโบสถ์รสแซ่บ", 60},
{"Wat Bot", "Rice", "ลาบปลาคังวัดโบสถ์พร้อมข้าว", 100},
{"Wat Bot", "Rice", "ครัวริมทางวัดโบสถ์ตามสั่ง", 55},
{"Wat Bot", "Rice", "ข้าวผัดกระเพราปลาแควน้อย", 80},

// --- Mueang Kamphaeng Phet ---
{"Mueang Kamphaeng Phet", "Noodle", "บะหมี่ชากังราว (ต้นตำรับ)", 50},
{"Mueang Kamphaeng Phet", "Noodle", "ก๋วยเตี๋ยวต้มยำโบราณชากังราว", 45},
{"Mueang Kamphaeng Phet", "Noodle", "บะหมี่เกี๊ยวทำเองหน้าตลาด", 50},
{"Mueang Kamphaeng Phet", "Noodle", "ก๋วยเตี๋ยวเรือปากทางชากังราว", 45},
{"Mueang Kamphaeng Phet", "Noodle", "ผัดไทยสุโขทัย (สาขากำแพงเพชร)", 55},
{"Mueang Kamphaeng Phet", "Rice", "ข้าวมันไก่ชากังราวเจ้าเก่า", 50},
{"Mueang Kamphaeng Phet", "Rice", "ข้าวหมูแดงเจ๊มวย", 50},
{"Mueang Kamphaeng Phet", "Rice", "ข้าวขาหมูเพชรบุรี (สาขากำแพงเพชร)", 60},
{"Mueang Kamphaeng Phet", "Rice", "ครัวริมทางตามสั่งเมืองกำแพง", 60},
{"Mueang Kamphaeng Phet", "Rice", "ข้าวราดคะน้าหมูกรอบพุงกาง", 55},

// --- Pang Sila Thong ---
{"Pang Sila Thong", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นปางศิลาทอง", 50},
{"Pang Sila Thong", "Noodle", "บะหมี่เกี๊ยวน้านใสปางศิลา", 45},
{"Pang Sila Thong", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกปางศิลา", 45},
{"Pang Sila Thong", "Noodle", "เส้นเล็กต้มยำโบราณ", 50},
{"Pang Sila Thong", "Noodle", "ขนมจีนน้ำยากะทิป้าจันทร์", 40},
{"Pang Sila Thong", "Rice", "ข้าวมันไก่ปางศิลาทองรสเด็ด", 50},
{"Pang Sila Thong", "Rice", "ข้าวขาหมูสูตรโบราณปางศิลา", 55},
{"Pang Sila Thong", "Rice", "ลาบหมูปางศิลาพร้อมข้าว", 80},
{"Pang Sila Thong", "Rice", "ครัวปางศิลาตามสั่ง", 55},
{"Pang Sila Thong", "Rice", "ข้าวหน้าหมูทอดรสแซ่บ", 50},

// --- Khlong Lan ---
{"Khlong Lan", "Noodle", "ก๋วยเตี๋ยวต้มยำน้ำตกคลองลาน", 55},
{"Khlong Lan", "Noodle", "บะหมี่หมูแดงคลองลานเจ้าเก่า", 50},
{"Khlong Lan", "Noodle", "ก๋วยเตี๋ยวเรือริมน้ำตก", 50},
{"Khlong Lan", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Khlong Lan", "Noodle", "ผัดไทยโบราณคลองลาน", 55},
{"Khlong Lan", "Rice", "ครัวน้ำตกคลองลานตามสั่ง", 90},
{"Khlong Lan", "Rice", "ข้าวมันไก่คลองลานรสเด็ด", 50},
{"Khlong Lan", "Rice", "ข้าวขาหมูคลองลานเจ้าเก่า", 60},
{"Khlong Lan", "Rice", "ลาบปลาคลองลานเสิร์ฟพร้อมข้าว", 100},
{"Khlong Lan", "Rice", "ข้าวราดพริกแกงหมูป่าคลองลาน", 75},

// --- Kosamphi Nakhon ---
{"Kosamphi Nakhon", "Noodle", "ก๋วยเตี๋ยวหมูหมักโกสัมพี", 45},
{"Kosamphi Nakhon", "Noodle", "บะหมี่น้ำใสโกสัมพีรสเด็ด", 45},
{"Kosamphi Nakhon", "Noodle", "ก๋วยเตี๋ยวเรือปากทางโกสัมพี", 45},
{"Kosamphi Nakhon", "Noodle", "เส้นเล็กต้มยำไข่หวาน", 55},
{"Kosamphi Nakhon", "Noodle", "เย็นตาโฟโกสัมพีโบราณ", 50},
{"Kosamphi Nakhon", "Rice", "ข้าวมันไก่โกสัมพีรสเลิศ", 50},
{"Kosamphi Nakhon", "Rice", "ข้าวขาหมูโกสัมพีเจ้าเก่า", 55},
{"Kosamphi Nakhon", "Rice", "ครัวโกสัมพีอาหารตามสั่ง", 55},
{"Kosamphi Nakhon", "Rice", "ลาบไก่โกสัมพีพร้อมข้าว", 80},
{"Kosamphi Nakhon", "Rice", "ข้าวหน้าหมูกรอบโกสัมพี", 65},

// --- Phran Kratai ---
{"Phran Kratai", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นพรานกระต่าย", 50},
{"Phran Kratai", "Noodle", "บะหมี่เกี๊ยวพรานกระต่ายรสเด็ด", 50},
{"Phran Kratai", "Noodle", "ก๋วยเตี๋ยวเนื้อน้ำตกพรานกระต่าย", 60},
{"Phran Kratai", "Noodle", "เส้นเล็กต้มยำแห้งพรานกระต่าย", 50},
{"Phran Kratai", "Noodle", "ผัดไทยพรานกระต่ายโบราณ", 60},
{"Phran Kratai", "Rice", "ข้าวมันไก่พรานกระต่ายเจ้าเก่า", 50},
{"Phran Kratai", "Rice", "ข้าวขาหมูพรานกระต่ายรสแซ่บ", 60},
{"Phran Kratai", "Rice", "ครัวพรานกระต่ายตามสั่ง", 55},
{"Phran Kratai", "Rice", "ข้าวหน้าเป็ดพรานกระต่าย", 75},
{"Phran Kratai", "Rice", "ลาบปลาพรานกระต่ายเสิร์ฟพร้อมข้าว", 90},

// --- Mueang Phetchabun ---
{"Mueang Phetchabun", "Noodle", "ก๋วยเตี๋ยวเนื้อตุ๋นเพชรบูรณ์", 60},
{"Mueang Phetchabun", "Noodle", "ขนมจีนเสวยเมธาวี", 45},
{"Mueang Phetchabun", "Noodle", "บะหมี่หมูแดงตลาดเทศบาล", 50},
{"Mueang Phetchabun", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกริมทาง", 45},
{"Mueang Phetchabun", "Noodle", "เย็นตาโฟเพชรบูรณ์รสแซ่บ", 50},
{"Mueang Phetchabun", "Rice", "ไก่ย่างวิเชียรบุรี (สาขาเมืองเพชร)", 150},
{"Mueang Phetchabun", "Rice", "ข้าวมันไก่เพชรบูรณ์เจ้าเก่า", 50},
{"Mueang Phetchabun", "Rice", "ข้าวขาหมูเพชรบูรณ์รสเด็ด", 60},
{"Mueang Phetchabun", "Rice", "ข้าวหน้าเป็ดเมืองเพชร", 75},
{"Mueang Phetchabun", "Rice", "ครัวบ้านสวนตามสั่ง", 60},

// --- Si Thep ---
{"Si Thep", "Noodle", "ก๋วยเตี๋ยวอุทยานประวัติศาสตร์ศรีเทพ", 50},
{"Si Thep", "Noodle", "บะหมี่น้ำใสศรีเทพโบราณ", 45},
{"Si Thep", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกศรีเทพ", 45},
{"Si Thep", "Noodle", "ขนมจีนน้ำยากะทิป้าแดง", 40},
{"Si Thep", "Noodle", "เส้นเล็กต้มยำไข่เค็ม", 55},
{"Si Thep", "Rice", "ข้าวมันไก่ศรีเทพรสเด็ด", 50},
{"Si Thep", "Rice", "ข้าวขาหมูศรีเทพเจ้าเก่า", 55},
{"Si Thep", "Rice", "ลาบไก่ศรีเทพพร้อมข้าวเหนียว", 80},
{"Si Thep", "Rice", "ครัวศรีเทพอาหารตามสั่ง", 55},
{"Si Thep", "Rice", "ข้าวหน้าหมูกรอบศรีเทพ", 60},

// --- Khao Kho ---
{"Khao Kho", "Noodle", "ก๋วยเตี๋ยวเรือยอดดอยเขาค้อ", 60},
{"Khao Kho", "Noodle", "ข้าวซอยไก่เขาค้อ", 70},
{"Khao Kho", "Noodle", "บะหมี่น้ำหมูย่างเขาค้อ", 65},
{"Khao Kho", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นสมุนไพร", 60},
{"Khao Kho", "Noodle", "ผัดไทยกุ้งสดเขาค้อ", 85},
{"Khao Kho", "Rice", "ข้าวขาหมูเยอรมันเขาค้อ", 250},
{"Khao Kho", "Rice", "ข้าวผัดน้ำพริกเขาค้อ", 90},
{"Khao Kho", "Rice", "ครัวไร่กำนันจุล (เมนูข้าว)", 120},
{"Khao Kho", "Rice", "ข้าวหน้าไก่ทอดซอสเขาค้อ", 80},
{"Khao Kho", "Rice", "ลาบหมูชาวดอยพร้อมข้าว", 90},

// --- Lom Kao ---
{"Lom Kao", "Noodle", "ขนมจีนหล่มเก่า (ป้ากาล)", 40},
{"Lom Kao", "Noodle", "ขนมจีนเจ๊แร่หล่มเก่า", 40},
{"Lom Kao", "Noodle", "ก๋วยเตี๋ยวหมูโบราณหล่มเก่า", 45},
{"Lom Kao", "Noodle", "บะหมี่น้ำใสหล่มเก่า", 45},
{"Lom Kao", "Noodle", "ราดหน้ายอดผักหล่มเก่า", 50},
{"Lom Kao", "Rice", "ข้าวมันไก่หล่มเก่ารสเลิศ", 50},
{"Lom Kao", "Rice", "ข้าวขาหมูหล่มเก่ารสเด็ด", 60},
{"Lom Kao", "Rice", "ครัวหล่มเก่าตามสั่ง", 55},
{"Lom Kao", "Rice", "ลาบไก่หล่มเก่าพร้อมข้าว", 80},
{"Lom Kao", "Rice", "ข้าวแกงแม่สมใจหล่มเก่า", 40},

// --- Lom Sak ---
{"Lom Sak", "Noodle", "ก๋วยเตี๋ยวเรือหล่มสักรสเด็ด", 50},
{"Lom Sak", "Noodle", "บะหมี่เกี๊ยวทำเองหล่มสัก", 50},
{"Lom Sak", "Noodle", "ขนมจีนน้ำยาหล่มสักเจ้าเก่า", 40},
{"Lom Sak", "Noodle", "เส้นเล็กต้มยำสุโขทัย (หล่มสัก)", 50},
{"Lom Sak", "Noodle", "เย็นตาโฟหล่มสักโบราณ", 50},
{"Lom Sak", "Rice", "ข้าวหมูแดงหล่มสักเลิศรส", 55},
{"Lom Sak", "Rice", "ข้าวมันไก่หล่มสักเจ้าเก่า", 50},
{"Lom Sak", "Rice", "ข้าวขาหมูหล่มสักรสแซ่บ", 60},
{"Lom Sak", "Rice", "ครัวหล่มสักอาหารตามสั่ง", 60},
{"Lom Sak", "Rice", "ข้าวหน้าเป็ดหล่มสัก", 75},

// --- Nam Nao ---
{"Nam Nao", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นน้ำหนาว", 50},
{"Nam Nao", "Noodle", "บะหมี่น้ำใสน้ำหนาวดอยสูง", 50},
{"Nam Nao", "Noodle", "เส้นเล็กต้มยำน้ำข้นป่าสน", 55},
{"Nam Nao", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกน้ำหนาว", 45},
{"Nam Nao", "Noodle", "ขนมจีนน้ำยากะทิน้ำหนาว", 40},
{"Nam Nao", "Rice", "ข้าวมันไก่น้ำหนาวรสเด็ด", 50},
{"Nam Nao", "Rice", "ข้าวขาหมูน้ำหนาวเจ้าเก่า", 60},
{"Nam Nao", "Rice", "ลาบหมูป่าน้ำหนาวพร้อมข้าว", 100},
{"Nam Nao", "Rice", "ครัวน้ำหนาวตามสั่ง", 70},
{"Nam Nao", "Rice", "ข้าวหน้าหมูกรอบน้ำหนาว", 65},

// --- Wang Pong ---
{"Wang Pong", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นวังโป่ง", 50},
{"Wang Pong", "Noodle", "บะหมี่เกี๊ยววังโป่งรสเด็ด", 50},
{"Wang Pong", "Noodle", "เส้นเล็กต้มยำแห้งวังโป่ง", 50},
{"Wang Pong", "Noodle", "ก๋วยเตี๋ยวเรือปากทางวังโป่ง", 45},
{"Wang Pong", "Noodle", "ผัดไทยโบราณวังโป่ง", 55},
{"Wang Pong", "Rice", "ข้าวมันไก่วังโป่งเจ้าเก่า", 50},
{"Wang Pong", "Rice", "ข้าวขาหมูวังโป่งรสแซ่บ", 60},
{"Wang Pong", "Rice", "ลาบปลาวังโป่งพร้อมข้าว", 90},
{"Wang Pong", "Rice", "ครัววังโป่งอาหารตามสั่ง", 55},
{"Wang Pong", "Rice", "ข้าวราดพริกแกงหมูกรอบ", 60},

// --- Mueang Phichit ---
{"Mueang Phichit", "Noodle", "ก๋วยเตี๋ยวต้มยำหมูสะเต๊ะพิจิตร", 50},
{"Mueang Phichit", "Noodle", "บะหมี่เกี๊ยวทำเองหน้าตลาด", 50},
{"Mueang Phichit", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกพิจิตรรสเด็ด", 45},
{"Mueang Phichit", "Noodle", "เย็นตาโฟพิจิตรโบราณ", 50},
{"Mueang Phichit", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นปลาแม่น้ำ", 50},
{"Mueang Phichit", "Rice", "ข้าวมันไก่พิจิตรเจ้าเก่า", 50},
{"Mueang Phichit", "Rice", "ข้าวหมูแดงเจ๊จูพิจิตร", 50},
{"Mueang Phichit", "Rice", "ข้าวขาหมูเพชรบุรี (สาขาพิจิตร)", 60},
{"Mueang Phichit", "Rice", "ครัวริมทางตามสั่งเมืองพิจิตร", 60},
{"Mueang Phichit", "Rice", "ข้าวหน้าเป็ดพิจิตรเลิศรส", 75},

// --- Pho Prathap Chang ---
{"Pho Prathap Chang", "Noodle", "ก๋วยเตี๋ยวต้มยำวัดโพธิ์ประทับช้าง", 45},
{"Pho Prathap Chang", "Noodle", "บะหมี่หมูแดงโพธิ์ประทับช้าง", 45},
{"Pho Prathap Chang", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกท่าบัว", 45},
{"Pho Prathap Chang", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Pho Prathap Chang", "Noodle", "ผัดไทยโบราณโพธิ์ประทับช้าง", 50},
{"Pho Prathap Chang", "Rice", "ข้าวมันไก่โพธิ์ประทับช้างรสเด็ด", 45},
{"Pho Prathap Chang", "Rice", "ข้าวขาหมูโพธิ์ประทับช้างเจ้าเก่า", 55},
{"Pho Prathap Chang", "Rice", "ลาบหมูโพธิ์ประทับช้างพร้อมข้าว", 80},
{"Pho Prathap Chang", "Rice", "ครัวส้มตำริมทางโพธิ์ประทับช้าง", 70},
{"Pho Prathap Chang", "Rice", "ข้าวราดกะเพราปลาแม่น้ำ", 60},

// --- Sam Ngam ---
{"Sam Ngam", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นสามง่ามรสเด็ด", 50},
{"Sam Ngam", "Noodle", "บะหมี่น้ำใสสามง่ามเจ้าเก่า", 45},
{"Sam Ngam", "Noodle", "เย็นตาโฟสามง่ามโบราณ", 50},
{"Sam Ngam", "Noodle", "เส้นเล็กต้มยำไข่เค็ม", 55},
{"Sam Ngam", "Noodle", "ก๋วยเตี๋ยวเรือปากทางสามง่าม", 45},
{"Sam Ngam", "Rice", "ข้าวมันไก่ตอนสามง่ามเลิศรส", 50},
{"Sam Ngam", "Rice", "ข้าวขาหมูสามง่ามรสแซ่บ", 60},
{"Sam Ngam", "Rice", "ลาบปลาสามง่ามพร้อมข้าวเหนียว", 90},
{"Sam Ngam", "Rice", "ครัวสามง่ามอาหารตามสั่ง", 55},
{"Sam Ngam", "Rice", "ข้าวราดพริกแกงหมูป่าสามง่าม", 75},

// --- Thap Khlo ---
{"Thap Khlo", "Noodle", "ก๋วยเตี๋ยวหมูหมักทับคล้อรสเด็ด", 45},
{"Thap Khlo", "Noodle", "บะหมี่เกี๊ยวทับคล้อเจ้าเก่า", 50},
{"Thap Khlo", "Noodle", "เส้นเล็กต้มยำน้ำข้นทับคล้อ", 50},
{"Thap Khlo", "Noodle", "ราดหน้ายอดผักทับคล้อ", 55},
{"Thap Khlo", "Noodle", "ก๋วยเตี๋ยวเนื้อตุ๋นทับคล้อ", 65},
{"Thap Khlo", "Rice", "ข้าวมันไก่ทับคล้อรสเลิศ", 50},
{"Thap Khlo", "Rice", "ข้าวขาหมูทับคล้อรสเด็ด", 60},
{"Thap Khlo", "Rice", "ข้าวหมูแดงทับคล้อเจ้าดัง", 55},
{"Thap Khlo", "Rice", "ครัวทับคล้ออาหารตามสั่ง", 60},
{"Thap Khlo", "Rice", "ลาบไก่ทับคล้อพร้อมข้าวเหนียว", 80},

// --- Bang Mun Nak ---
{"Bang Mun Nak", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นบางมูลนาก", 50},
{"Bang Mun Nak", "Noodle", "บะหมี่น้ำใสบางมูลนากรสเด็ด", 45},
{"Bang Mun Nak", "Noodle", "เย็นตาโฟบางมูลนากโบราณ", 50},
{"Bang Mun Nak", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกบางมูลนาก", 45},
{"Bang Mun Nak", "Noodle", "ผัดไทยโบราณบางมูลนาก", 50},
{"Bang Mun Nak", "Rice", "ข้าวมันไก่บางมูลนากเจ้าเก่า", 50},
{"Bang Mun Nak", "Rice", "ข้าวขาหมูบางมูลนากรสแซ่บ", 60},
{"Bang Mun Nak", "Rice", "ข้าวหมูแดงบางมูลนากเลิศรส", 55},
{"Bang Mun Nak", "Rice", "ครัวบางมูลนากตามสั่ง", 55},
{"Bang Mun Nak", "Rice", "ข้าวราดพริกแกงปลาแม่น้ำ", 85},

// --- Pho Thale ---
{"Pho Thale", "Noodle", "ก๋วยเตี๋ยวต้มยำวัดบางคลาน", 50},
{"Pho Thale", "Noodle", "บะหมี่หมูแดงโพทะเลรสเด็ด", 45},
{"Pho Thale", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกโพทะเล", 45},
{"Pho Thale", "Noodle", "เส้นเล็กน้ำใสโพทะเล", 45},
{"Pho Thale", "Noodle", "ขนมจีนน้ำยากะทิป้าหวัง", 40},
{"Pho Thale", "Rice", "ข้าวมันไก่โพทะเลรสเด็ด", 50},
{"Pho Thale", "Rice", "ข้าวขาหมูโพทะเลเจ้าเก่า", 55},
{"Pho Thale", "Rice", "ลาบหมูโพทะเลพร้อมข้าว", 80},
{"Pho Thale", "Rice", "ครัวโพทะเลอาหารตามสั่ง", 55},
{"Pho Thale", "Rice", "ข้าวหน้าหมูทอดโพทะเล", 50},

// --- Mueang Nakhon Sawan ---
{"Mueang Nakhon Sawan", "Noodle", "ก๋วยเตี๋ยวลูกชิ้นปลากราย (นายซุ้ย)", 60},
{"Mueang Nakhon Sawan", "Noodle", "ก๋วยเตี๋ยวลิ้นวัวโกเนี้ยว", 80},
{"Mueang Nakhon Sawan", "Noodle", "ราดหน้าเอ็มไพร์ปากน้ำโพ", 55},
{"Mueang Nakhon Sawan", "Noodle", "ผัดไทยแม่พะยอม", 60},
{"Mueang Nakhon Sawan", "Noodle", "บะหมี่เป็ดตุ๋นปากน้ำโพ", 70},
{"Mueang Nakhon Sawan", "Rice", "ข้าวมันไก่โกตี๋ปากน้ำโพ", 50},
{"Mueang Nakhon Sawan", "Rice", "ข้าวหมูแดงหนองสมบูรณ์", 55},
{"Mueang Nakhon Sawan", "Rice", "ข้าวขาหมูเสวยนครสวรรค์", 65},
{"Mueang Nakhon Sawan", "Rice", "ครัวต้นน้ำ (อาหารตามสั่ง)", 150},
{"Mueang Nakhon Sawan", "Rice", "ข้าวราดพริกแกงลูกชิ้นปลากราย", 85},

// --- Takhli ---
{"Takhli", "Noodle", "ก๋วยเตี๋ยวต้มยำตาคลีรสเด็ด", 50},
{"Takhli", "Noodle", "บะหมี่หมูแดงตาคลีเจ้าเก่า", 45},
{"Takhli", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกตาคลี", 45},
{"Takhli", "Noodle", "เย็นตาโฟตาคลีโบราณ", 50},
{"Takhli", "Noodle", "ผัดไทยโบราณตาคลี", 55},
{"Takhli", "Rice", "ข้าวมันไก่ตอนตาคลี", 50},
{"Takhli", "Rice", "ข้าวขาหมูตาคลีรสแซ่บ", 60},
{"Takhli", "Rice", "ข้าวหมูแดงตาคลีเลิศรส", 55},
{"Takhli", "Rice", "ครัวตาคลีตามสั่ง", 55},
{"Takhli", "Rice", "ลาบหมูตาคลีพร้อมข้าว", 80},

// --- Banphot Phisai ---
{"Banphot Phisai", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นบรรพตพิสัย", 50},
{"Banphot Phisai", "Noodle", "บะหมี่น้ำใสบรรพตพิสัย", 45},
{"Banphot Phisai", "Noodle", "เส้นเล็กต้มยำปลาแม่น้ำ", 60},
{"Banphot Phisai", "Noodle", "ก๋วยเตี๋ยวเรือปากทางบรรพต", 45},
{"Banphot Phisai", "Noodle", "ราดหน้ายอดผักบรรพตพิสัย", 55},
{"Banphot Phisai", "Rice", "ข้าวมันไก่บรรพตพิสัยรสเด็ด", 50},
{"Banphot Phisai", "Rice", "ข้าวขาหมูบรรพตพิสัยเจ้าเก่า", 55},
{"Banphot Phisai", "Rice", "ครัวริมทางบรรพตพิสัยตามสั่ง", 60},
{"Banphot Phisai", "Rice", "ข้าวหน้าหมูกรอบบรรพตพิสัย", 65},
{"Banphot Phisai", "Rice", "ลาบปลาแม่น้ำพร้อมข้าว", 90},

// --- Tha Tako ---
{"Tha Tako", "Noodle", "ก๋วยเตี๋ยวเรือท่าตะโกรสเด็ด", 45},
{"Tha Tako", "Noodle", "บะหมี่เกี๊ยวท่าตะก้อเจ้าเก่า", 50},
{"Tha Tako", "Noodle", "เย็นตาโฟท่าตะโกโบราณ", 50},
{"Tha Tako", "Noodle", "ก๋วยเตี๋ยวต้มยำไข่เค็มท่าตะโก", 55},
{"Tha Tako", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Tha Tako", "Rice", "ข้าวมันไก่ท่าตะโกเลิศรส", 50},
{"Tha Tako", "Rice", "ข้าวขาหมูท่าตะโกเจ้าเก่า", 55},
{"Tha Tako", "Rice", "ครัวท่าตะโกอาหารตามสั่ง", 55},
{"Tha Tako", "Rice", "ลาบหมูท่าตะโกพร้อมข้าว", 80},
{"Tha Tako", "Rice", "ข้าวราดพริกแกงหมูกรอบ", 60},

// --- Chum Saeng ---
{"Chum Saeng", "Noodle", "ก๋วยเตี๋ยวหมูโบราณชุมแสง", 45},
{"Chum Saeng", "Noodle", "บะหมี่เกี๊ยวชุมแสงรสเด็ด", 50},
{"Chum Saeng", "Noodle", "เย็นตาโฟชุมแสงเจ้าเก่า", 50},
{"Chum Saeng", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกริมทางชุมแสง", 45},
{"Chum Saeng", "Noodle", "ราดหน้าชุมแสงยอดผัก", 55},
{"Chum Saeng", "Rice", "ข้าวมันไก่ชุมแสงเลิศรส", 50},
{"Chum Saeng", "Rice", "ข้าวขาหมูชุมแสงรสเด็ด", 60},
{"Chum Saeng", "Rice", "ครัวชุมแสงตามสั่ง", 55},
{"Chum Saeng", "Rice", "ลาบปลาชุมแสงพร้อมข้าว", 90},
{"Chum Saeng", "Rice", "ข้าวหน้าหมูทอดชุมแสง", 55},

// --- Mae Poen ---
{"Mae Poen", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นแม่เปิน", 50},
{"Mae Poen", "Noodle", "บะหมี่น้ำใสแม่เปินดอยสูง", 50},
{"Mae Poen", "Noodle", "ก๋วยเตี๋ยวเรือปากทางแม่เปิน", 45},
{"Mae Poen", "Noodle", "เส้นเล็กต้มยำน้ำข้นแม่เปิน", 55},
{"Mae Poen", "Noodle", "ขนมจีนน้ำยากะทิป้าแดง", 40},
{"Mae Poen", "Rice", "ข้าวมันไก่แม่เปินรสเด็ด", 50},
{"Mae Poen", "Rice", "ข้าวขาหมูแม่เปินเจ้าเก่า", 60},
{"Mae Poen", "Rice", "ลาบหมูป่าแม่เปินพร้อมข้าว", 100},
{"Mae Poen", "Rice", "ครัวแม่เปินอาหารตามสั่ง", 70},
{"Mae Poen", "Rice", "ข้าวหน้าหมูกรอบแม่เปิน", 65},

// --- Chum Ta Bong ---
{"Chum Ta Bong", "Noodle", "ก๋วยเตี๋ยวไก่ตุ๋นชุมตาบง", 50},
{"Chum Ta Bong", "Noodle", "บะหมี่เกี๊ยวชุมตาบงรสเด็ด", 50},
{"Chum Ta Bong", "Noodle", "เส้นเล็กต้มยำแห้งชุมตาบง", 50},
{"Chum Ta Bong", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกชุมตาบง", 45},
{"Chum Ta Bong", "Noodle", "เย็นตาโฟชุมตาบงโบราณ", 50},
{"Chum Ta Bong", "Rice", "ข้าวมันไก่ชุมตาบงเจ้าเก่า", 50},
{"Chum Ta Bong", "Rice", "ข้าวขาหมูชุมตาบงรสแซ่บ", 60},
{"Chum Ta Bong", "Rice", "ครัวชุมตาบงตามสั่ง", 55},
{"Chum Ta Bong", "Rice", "ลาบไก่ชุมตาบงพร้อมข้าว", 80},
{"Chum Ta Bong", "Rice", "ข้าวหน้าหมูทอดชุมตาบง", 55},

// --- Tak Fa ---
{"Tak Fa", "Noodle", "ก๋วยเตี๋ยวต้มยำตากฟ้ารสแซ่บ", 50},
{"Tak Fa", "Noodle", "บะหมี่หมูแดงตากฟ้าเจ้าเก่า", 50},
{"Tak Fa", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกตากฟ้า", 45},
{"Tak Fa", "Noodle", "เย็นตาโฟตากฟ้าโบราณ", 50},
{"Tak Fa", "Noodle", "ราดหน้ายอดผักตากฟ้า", 55},
{"Tak Fa", "Rice", "ข้าวมันไก่ตากฟ้าเลิศรส", 50},
{"Tak Fa", "Rice", "ข้าวขาหมูตากฟ้าเจ้าเก่า", 55},
{"Tak Fa", "Rice", "ครัวตากฟ้าอาหารตามสั่ง", 60},
{"Tak Fa", "Rice", "ลาบหมูตากฟ้าพร้อมข้าว", 80},
{"Tak Fa", "Rice", "ข้าวหมูแดงตากฟ้ารสเด็ด", 55},

// --- Kao Liao ---
{"Kao Liao", "Noodle", "ก๋วยเตี๋ยวเรือเก้าเลี้ยวรสเด็ด", 45},
{"Kao Liao", "Noodle", "บะหมี่เกี๊ยวเก้าเลี้ยวเจ้าเก่า", 50},
{"Kao Liao", "Noodle", "เส้นเล็กต้มยำน้ำข้นเก้าเลี้ยว", 50},
{"Kao Liao", "Noodle", "เย็นตาโฟเก้าเลี้ยวหน้าตลาด", 50},
{"Kao Liao", "Noodle", "ผัดไทยโบราณเก้าเลี้ยว", 55},
{"Kao Liao", "Rice", "ข้าวมันไก่เก้าเลี้ยวเจ้าเก่า", 50},
{"Kao Liao", "Rice", "ข้าวขาหมูเก้าเลี้ยวรสแซ่บ", 60},
{"Kao Liao", "Rice", "ครัวเก้าเลี้ยวตามสั่ง", 55},
{"Kao Liao", "Rice", "ข้าวหมูแดงเก้าเลี้ยวเลิศรส", 55},
{"Kao Liao", "Rice", "ลาบปลาเก้าเลี้ยวพร้อมข้าว", 90},

// --- Phayuha Khiri ---
{"Phayuha Khiri", "Noodle", "ก๋วยเตี๋ยวลูกชิ้นปลาพยุหะขีรี", 60},
{"Phayuha Khiri", "Noodle", "บะหมี่หมูแดงพยุหะรสเด็ด", 50},
{"Phayuha Khiri", "Noodle", "ก๋วยเตี๋ยวเรือปากน้ำโพ (พยุหะ)", 50},
{"Phayuha Khiri", "Noodle", "เส้นเล็กต้มยำไข่เค็ม", 55},
{"Phayuha Khiri", "Noodle", "เย็นตาโฟพยุหะโบราณ", 50},
{"Phayuha Khiri", "Rice", "ข้าวมันไก่พยุหะรสเลิศ", 50},
{"Phayuha Khiri", "Rice", "ข้าวขาหมูพยุหะรสเด็ด", 60},
{"Phayuha Khiri", "Rice", "ครัวริมทางพยุหะตามสั่ง", 60},
{"Phayuha Khiri", "Rice", "ข้าวหน้าเป็ดพยุหะ", 75},
{"Phayuha Khiri", "Rice", "ลาบปลาแม่น้ำพยุหะพร้อมข้าว", 100},

// --- Mueang Uthai Thani ---
{"Mueang Uthai Thani", "Noodle", "ก๋วยเตี๋ยวไก่ไทใส่หน่อไม้ (เจ้าเก่า)", 50},
{"Mueang Uthai Thani", "Noodle", "บะหมี่ทำเองเจ๊เน้ยปากหมา", 50},
{"Mueang Uthai Thani", "Noodle", "ก๋วยเตี๋ยวปลาแรดลวกจิ้ม", 70},
{"Mueang Uthai Thani", "Noodle", "เย็นตาโฟริมน้ำสะแกกรัง", 50},
{"Mueang Uthai Thani", "Noodle", "เส้นเล็กต้มยำหมูโบราณ", 45},
{"Mueang Uthai Thani", "Rice", "ข้าวหน้าปลาแรดทอดกระเทียม", 120},
{"Mueang Uthai Thani", "Rice", "ข้าวมันไก่โกตี๋ (สาขาอุทัยธานี)", 50},
{"Mueang Uthai Thani", "Rice", "ข้าวหมูแดงพรหมท่าซุง", 55},
{"Mueang Uthai Thani", "Rice", "ครัวสะแกกรังอาหารตามสั่ง", 80},
{"Mueang Uthai Thani", "Rice", "ลาบปลาแรดพร้อมข้าวเหนียว", 100},

// --- Lan Sak ---
{"Lan Sak", "Noodle", "ก๋วยเตี๋ยวหมูตุ๋นลานสัก", 50},
{"Lan Sak", "Noodle", "บะหมี่น้ำใสลานสักรสเด็ด", 45},
{"Lan Sak", "Noodle", "ก๋วยเตี๋ยวเรือปากทางลานสัก", 45},
{"Lan Sak", "Noodle", "เส้นเล็กต้มยำหุบป่าตาด", 55},
{"Lan Sak", "Noodle", "เย็นตาโฟลานสักโบราณ", 50},
{"Lan Sak", "Rice", "ข้าวมันไก่ลานสักเจ้าเก่า", 50},
{"Lan Sak", "Rice", "ข้าวขาหมูลานสักรสแซ่บ", 60},
{"Lan Sak", "Rice", "ครัวหุบป่าตาดตามสั่ง", 70},
{"Lan Sak", "Rice", "ลาบหมูป่าลานสักพร้อมข้าว", 90},
{"Lan Sak", "Rice", "ข้าวหน้าหมูทอดลานสัก", 55},

// --- Ban Rai ---
{"Ban Rai", "Noodle", "ก๋วยเตี๋ยวต้มยำบ้านไร่รสเด็ด", 50},
{"Ban Rai", "Noodle", "บะหมี่หมูแดงบ้านไร่โบราณ", 50},
{"Ban Rai", "Noodle", "ก๋วยเตี๋ยวเรือน้ำตกบ้านไร่", 45},
{"Ban Rai", "Noodle", "ขนมจีนน้ำยากะทิป้าหวัง", 40},
{"Ban Rai", "Noodle", "เส้นเล็กน้ำใสลูกชิ้นเนื้อ", 50},
{"Ban Rai", "Rice", "ข้าวมันไก่บ้านไร่เลิศรส", 50},
{"Ban Rai", "Rice", "ข้าวขาหมูบ้านไร่เจ้าเก่า", 55},
{"Ban Rai", "Rice", "ลาบไก่บ้านไรพร้อมข้าว", 80},
{"Ban Rai", "Rice", "ครัวป่าบ้านไร่ตามสั่ง", 80},
{"Ban Rai", "Rice", "ข้าวหน้าหมูกรอบบ้านไร่", 65}
};
